/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: is the process up? No dependencies checked on purpose.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: can we actually reach the database?
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Proves the whole token-verification pipeline end to end over real
         *     HTTP - see ADR 0023. Not nested under /tenants/{tenant_id}/... - this
         *     is about the caller's own identity across every tenant they belong to,
         *     not scoped to one.
         *
         *     Re-fetched with memberships eager-loaded rather than reusing the
         *     `user` CurrentUser resolved - that one only ever needs `.id` itself.
         *
         *     Players/campaign_gm_grants (ADR 0031/RFC 0004) are resolved tenant by
         *     tenant, deliberately not in one eager-loaded query off `user`. `Player`/
         *     `CampaignGm` rows self-authorize via `user_id` regardless of
         *     `app.tenant_id` (ADR 0030's addendum), but what each one references -
         *     `character_player`/`character`/`being`/`entity` via `Player`; `Campaign`
         *     via `CampaignGm` - has no `user_id` column of its own for RLS to
         *     self-authorize against, and this user's players/GM grants can
         *     legitimately span *multiple* tenants, so there is no single
         *     `app.tenant_id` that would correctly authorize all of them at once
         *     regardless (unlike `/me`'s own memberships, campaign_gm, and player
         *     rows themselves). Confirmed empirically, not assumed: querying this
         *     chain with `app.tenant_id` never set at all raises
         *     `UndefinedObjectError`, the same "genuinely never set" failure mode
         *     every other RLS-protected table already has - `player`/`campaign_gm`
         *     just happen to have a `user_id`-based escape hatch, and nothing past
         *     them does.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenants
         * @description Every tenant the caller belongs to in *any* capacity - a Membership
         *     row, a Player row, or a CampaignGm row, anywhere in it (ADR 0030/RFC
         *     0003). Filtered directly in SQL via EXISTS (not combined in Python the
         *     way information_visibility.resolve_information_visibility does it) so
         *     real pagination works over an arbitrarily large tenant list - unlike
         *     that module's use case, this one needs Page[...]/apaginate's LIMIT/
         *     OFFSET to operate on one real query, not a small in-memory id set.
         */
        get: operations["list_tenants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tenant */
        get: operations["get_tenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tenant Roster
         * @description Broadened from a pure membership list to the tenant's full roster -
         *     every user with *any* standing in this tenant, not just its tenant-wide
         *     admins (ADR 0031/RFC 0004). One row per relationship, not per user - a
         *     user who is ORGA, GMs one campaign, and plays in another appears three
         *     times. Still gated by get_tenant_context, unchanged: an ordinary player
         *     doesn't need this to find their own standing, `/me` already covers that.
         *
         *     Combined in Python from three separate queries (mirroring
         *     resolve_information_visibility's own precedent), not one SQL UNION -
         *     the three row shapes are genuinely heterogeneous, and this is
         *     tenant-admin-only, so the data is bounded by how many people administer
         *     one world, not by total tenant traffic - paginating the already-fetched
         *     list, not the query, is a reasonable trade at that scale.
         */
        get: operations["list_tenant_roster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Campaigns
         * @description The tenant's campaign catalog - gated by is_tenant_participant (any
         *     Membership/Player/CampaignGm row anywhere in the tenant), not
         *     get_tenant_context, per ADR 0030/RFC 0003. Secret campaigns are then
         *     filtered per row: included only if the caller is that campaign's own GM
         *     or a tenant admin - a plain Player of a secret campaign they don't GM
         *     doesn't see it here either (they already know about it directly via
         *     their own `/me` response, RFC 0004).
         */
        get: operations["list_campaigns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/campaigns/{campaign_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Campaign
         * @description Unaffected by `secret` - get_campaign_context already only admits a
         *     player, a GM, or a tenant admin of this specific campaign; secret only
         *     governs the general browse-all list above, not whether someone who
         *     already has a legitimate way to reach it can open it directly (ADR
         *     0030/RFC 0003, same shape as a private GitHub repo).
         */
        get: operations["get_campaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/campaigns/{campaign_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/campaigns/{campaign_id}/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Player
         * @description Same shape as PlayerOut (RFC 0004: Player has no columns the
         *     summary omits) - its own schema/route anyway, matching the RFC's own
         *     endpoint table.
         */
        get: operations["get_player"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/campaigns/{campaign_id}/gms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gms
         * @description Unpaginated - matching OwnedByResponse's existing precedent of
         *     skipping pagination for a collection inherently small and bounded by
         *     construction (ADR 0031/RFC 0004).
         */
        get: operations["list_gms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Characters
         * @description Specifically a roster of Character rows, not every Being - a bare
         *     being with no character row doesn't appear here at all (ADR 0031/RFC
         *     0004).
         */
        get: operations["list_characters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/payloads/{payload_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Payload Content
         * @description Raw bytes for a picture/document payload, with the correct
         *     Content-Type - and Content-Disposition for documents - rather than
         *     embedding the bytes inline in a JSON response. See ADR 0020.
         *
         *     Same information_visibility check as GET /entities/{id} (ADR 0028's
         *     addendum) - a payload is only as visible as the Information it
         *     belongs to. "Doesn't exist," "wrong tenant," and "exists but you can't
         *     see its information" all raise the exact same PayloadNotFoundError,
         *     same body - matching get_tenant_context's own established precedent
         *     (ADR 0023) of not letting a caller distinguish "not found" from
         *     "found, but not for you."
         */
        get: operations["payload_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description A lightweight listing - EntitySummary rather than EntityDetailOut, to
         *     avoid an N+1-heavy response when listing many entities.
         */
        get: operations["list_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description The full detail shape, with every relationship eager-loaded up front.
         *
         *     Queried directly with the full .options() chain rather than delegating
         *     to dependencies.get_entity_or_404 first - that helper's plain
         *     session.get() wouldn't have any of these relationships loaded, so
         *     reusing it here would just mean a second, redundant round trip for
         *     this same row. The 404 check below covers exactly what that helper
         *     covers (missing id, or an id that belongs to a different tenant).
         */
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description Every base item type for this tenant - see ADR 0019/0020. Explicit
         *     tenant_id filter as defense in depth alongside RLS, not a replacement
         *     for it (ADR 0002/0021).
         */
        get: operations["list_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/items/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Item Instances
         * @description Every item instance for this tenant, optionally filtered to one
         *     container's contents (?container_id=&recursive=). `recursive` defaults
         *     to false - the costlier, cycle-risk-bearing traversal is explicit
         *     opt-in, not the default (ADR 0020 / task brief) - consistent with
         *     owned-by-grouped below also being non-recursive by design. Filtering by
         *     container is an ordinary query-param filter on this same list, unlike
         *     the structurally-different owned-by grouping, which is its own
         *     endpoint (ADR 0020).
         */
        get: operations["list_item_instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances/owned-by/{owner_entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Item Instances Owned By
         * @description Every item instance owned by owner_entity_id, grouped by *direct*
         *     container only (a None group for uncontained instances) - a one-level
         *     grouping, not a recursive container-tree walk. Deliberately not
         *     paginated - bounded by one owner's inventory (ADR 0020 / task brief).
         */
        get: operations["list_item_instances_owned_by"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item Instance
         * @description Not in the original task brief, added for REST symmetry with
         *     GET /items/{entity_id} - a resource with a list and filtered views but
         *     no direct single-item lookup by id would be a real gap.
         *
         *     Registered *after* /owned-by/{owner_entity_id} above - FastAPI/Starlette
         *     matches routes in registration order, and a wildcard path segment here
         *     would otherwise greedily match "owned-by" as an entity_id and shadow
         *     that route entirely. Confirmed empirically (not just reasoned through)
         *     that getting this order backwards really does break /owned-by/... with
         *     a 422, not just in theory.
         */
        get: operations["get_item_instance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CampaignOut
         * @description GET /tenants/{id}/campaigns/{id} - the full detail shape.
         *     Deliberately doesn't expose entity_id: it's an internal attachment
         *     point for Information/Knowledge, not something a client addresses
         *     directly yet (ADR 0030/RFC 0003). created_by/updated_by are bare
         *     user_ids (ADR 0029) - resolving one to a display name is a client
         *     concern this API doesn't store data for.
         */
        CampaignOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Game System */
            game_system: string;
            /** Secret */
            secret: boolean;
            /** Created By */
            created_by: string | null;
            /** Updated By */
            updated_by: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CampaignSummaryOut
         * @description One row of `GET /tenants/{id}/campaigns` - lean on purpose, matching
         *     every other *SummaryOut shape in this API (ADR 0020). See ADR 0030/RFC
         *     0003.
         */
        CampaignSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Game System */
            game_system: string;
            /** Secret */
            secret: boolean;
        };
        /**
         * CharacterOut
         * @description GET /tenants/{id}/characters/{id} - see ADR 0031/RFC 0004.
         *     `created_by`/`updated_by` are this row's own (ADR 0029) - who
         *     *promoted* this being into a tracked character, not who created the
         *     underlying `being` (that's `entity.created_by`, a different, also
         *     meaningful fact - ADR 0029's own open question).
         *
         *     `players` reuses `PlayerSummaryOut` whole (RFC 0004's own accepted
         *     minor redundancy: each returned player entry redundantly re-includes
         *     the very character being viewed, among any others that player
         *     controls - not worth a fourth schema variant to trim).
         *
         *     `PlayerSummaryOut` (schemas/players.py) needs `CharacterSummaryOut`
         *     right back - a genuine two-way schema reference, not an accident.
         *     Broken here the standard way: `PlayerSummaryOut` only appears under
         *     `TYPE_CHECKING` (so this module never really imports players.py,
         *     which itself really imports this one for `CharacterSummaryOut` above
         *     - a real cycle either direction if both were real imports), and
         *     `from_character` below imports it locally, deferred until actually
         *     called. Whatever first imports `routers/characters.py` calls
         *     `CharacterOut.model_rebuild(...)` to make the forward reference
         *     resolvable - see that module.
         */
        CharacterOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Name */
            name: string;
            /** Is Pc */
            is_pc: boolean;
            /** Owner Player Id */
            owner_player_id: string | null;
            /** Players */
            players: components["schemas"]["PlayerSummaryOut"][];
            /** Created By */
            created_by: string | null;
            /** Updated By */
            updated_by: string | null;
        };
        /**
         * CharacterSummaryOut
         * @description Identity/roster shape, not the fuller narrative view `v_character`
         *     exists for - see ADR 0031/RFC 0004. `name` is plain `Entity.name` (the
         *     internal/reference name, ADR 0012), not `v_character.title` - reaching
         *     for the view here would just be a second, unnecessary join. `is_pc` is
         *     RFC 0001/0002's derived fact (`owner_player_id IS NOT NULL`), computed
         *     here, not stored.
         *
         *     Requires `character.being.entity` eager-loaded first (`lazy=
         *     "raise_on_sql"`, ADR 0018) - raises rather than silently lazy-loading
         *     if the caller forgot.
         */
        CharacterSummaryOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Name */
            name: string;
            /** Is Pc */
            is_pc: boolean;
        };
        /**
         * DescriptionOut
         * @description Wraps one entry of `EntityViewMixin.descriptions` - see ADR 0020: the
         *     raw `tuple[str, str]` is a fine internal shape but a weak external JSON
         *     contract (no field names), so it's wrapped into a small named schema.
         */
        DescriptionOut: {
            /** Content */
            content: string;
            /** Locale */
            locale: string;
        };
        /**
         * EntityDetailOut
         * @description The full shape of a single entity - every relationship resolved and
         *     inlined. See ADR 0020. Deliberately not reused for the list endpoint,
         *     which returns EntitySummary instead to avoid an N+1-heavy response
         *     when listing many entities.
         */
        EntityDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Stats */
            stats: components["schemas"]["lorenzo_api__schemas__entities__StatValueOut"][];
            /** Stat Groups */
            stat_groups: components["schemas"]["EntitySummary"][];
            /** Information */
            information: components["schemas"]["InformationOut"][];
            /** Prototypes */
            prototypes: components["schemas"]["EntitySummary"][];
            /** Instances */
            instances: components["schemas"]["EntitySummary"][];
            parent: components["schemas"]["EntitySummary"] | null;
            /** Children */
            children: components["schemas"]["EntitySummary"][];
        };
        /**
         * EntitySummary
         * @description A lightweight entity reference - used anywhere an entity is pointed
         *     at generically (a container, a prototype, an owner) rather than fully
         *     described. See ADR 0020.
         */
        EntitySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * GmOut
         * @description One row of GET .../campaigns/{id}/gms - campaign_id/tenant_id are
         *     already in the path, no need to repeat them per row. See ADR 0031/RFC
         *     0004; fits here rather than a one-class module of its own, alongside
         *     campaign-roster concerns generally.
         */
        GmOut: {
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * GmRosterEntryOut
         * @description One row per CampaignGm row in the tenant. No `characters` field -
         *     GM-ing isn't tied to any character; a GM who also plays a PC already
         *     gets their own separate player-kind row for that.
         *
         *     RFC 0004's own shape also carries `created_by` (matching
         *     `campaign_gm`'s eventual lighter, create-only attribution shape - no
         *     `updated_by`, since a grant is never "updated," only made or revoked).
         *     Deliberately not included yet: per ADR 0029's phased table,
         *     `campaign_gm.created_by` itself doesn't land until campaign CRUD (ADR
         *     0034/RFC 0006) actually writes to this table - exposing a column that
         *     doesn't exist would be building ahead of that slice, not this one.
         *     Add it here as a small, natural follow-up once ADR 0034 lands.
         */
        GmRosterEntryOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "gm";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
        };
        /** RequestValidationError */
        HTTPValidationError: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            errors: components["schemas"]["ValidationError"][];
        };
        /**
         * InformationOut
         * @description A titled, categorized piece of information about an entity, with its
         *     payloads already resolved to their concrete kind - see ADR 0020. A
         *     single Information row's payloads can be of heterogeneous kinds, so
         *     each is resolved independently via payload_to_schema rather than
         *     assuming one kind per row.
         */
        InformationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Payloads */
            payloads: (components["schemas"]["PayloadDescriptionOut"] | components["schemas"]["PayloadNumberOut"] | components["schemas"]["PayloadPictureOut"] | components["schemas"]["PayloadDocumentOut"])[];
        };
        /**
         * ItemInstanceOut
         * @description A specific, ownable item ("My Shovel"), from `VItemInstance` -
         *     identical to `ItemOut` plus `owner_entity_id`. See ADR 0019/0020 and
         *     `ItemOut`'s docstring for the eager-load requirement.
         */
        ItemInstanceOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Owner Entity Id */
            owner_entity_id: string | null;
            /** Title */
            title: string | null;
            /** Weight */
            weight: number | null;
            /** Height */
            height: number | null;
            /** Price */
            price: number | null;
            /** Rarity */
            rarity: number | null;
            /** Hp */
            hp: number | null;
            /** Armor */
            armor: number | null;
            /** Container Entity Id */
            container_entity_id: string | null;
            /** Is Magical */
            is_magical: boolean | null;
            /** Is Cursed */
            is_cursed: boolean | null;
            /** Descriptions */
            descriptions: components["schemas"]["DescriptionOut"][];
            /** Pictures */
            pictures: components["schemas"]["PictureRefOut"][];
            /** Physical Stats */
            physical_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Economic Stats */
            economic_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Destroyable Stats */
            destroyable_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Damaging Stats */
            damaging_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Tags */
            tags: components["schemas"]["TagValueOut"][];
        };
        /**
         * ItemOut
         * @description A base item type ("Shovel"), from `VItem` - see ADR 0019/0020.
         *
         *     Constructing this requires the source `VItem` to already have its
         *     entity->information->payloads->description/picture,
         *     entity->information->knowledge_links (ADR 0028 - `descriptions` is
         *     visibility-gated, not a bare property anymore), and
         *     entity->stats->stat_definition->stat_group eager-loaded (see
         *     `routers.items.eager_load_options`, the exact recipe proven in
         *     `tests/test_v_item.py`) - the six wrapped properties/methods raise
         *     MissingGreenlet otherwise, they do not silently lazy-load.
         */
        ItemOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Title */
            title: string | null;
            /** Weight */
            weight: number | null;
            /** Height */
            height: number | null;
            /** Price */
            price: number | null;
            /** Rarity */
            rarity: number | null;
            /** Hp */
            hp: number | null;
            /** Armor */
            armor: number | null;
            /** Container Entity Id */
            container_entity_id: string | null;
            /** Is Magical */
            is_magical: boolean | null;
            /** Is Cursed */
            is_cursed: boolean | null;
            /** Descriptions */
            descriptions: components["schemas"]["DescriptionOut"][];
            /** Pictures */
            pictures: components["schemas"]["PictureRefOut"][];
            /** Physical Stats */
            physical_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Economic Stats */
            economic_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Destroyable Stats */
            destroyable_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Damaging Stats */
            damaging_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Tags */
            tags: components["schemas"]["TagValueOut"][];
        };
        /**
         * MeOut
         * @description The caller's own identity, tenant-wide memberships, campaign
         *     memberships, and GM grants - see ADR 0023/0031. `players`/
         *     `campaign_gm_grants` (ADR 0031/RFC 0004) are the concrete answer to
         *     "user -> owner|orga|member of tenant -> [player(campaign) ->
         *     character | GM(campaign)]" for the caller's own identity - the single
         *     place a client reads "everything I am, everywhere."
         */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Authgear Subject Id */
            authgear_subject_id: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
            /** Players */
            players: components["schemas"]["PlayerSummaryOut"][];
            /** Campaign Gm Grants */
            campaign_gm_grants: components["schemas"]["CampaignSummaryOut"][];
        };
        /**
         * MembershipOut
         * @description A tenant-wide administrative access grant - see ADR 0022/0023.
         */
        MembershipOut: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Role */
            role: string;
        };
        /**
         * MembershipRosterEntryOut
         * @description One row of GET /tenants/{id}/memberships' broadened roster (ADR
         *     0031/RFC 0004) - see TenantRosterEntryOut below for why this is a
         *     discriminated union rather than one schema with sometimes-meaningful
         *     fields, matching the PayloadOut precedent (ADR 0020).
         *
         *     RFC 0004's own shape also carries `created_by`/`updated_by`.
         *     Deliberately not included yet: per ADR 0029's phased table,
         *     `membership`'s attribution pair doesn't land until user/player/
         *     character CRUD (ADR 0036/RFC 0007) actually writes to this table -
         *     add it here as a small follow-up once that lands.
         */
        MembershipRosterEntryOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "membership";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Role */
            role: string;
        };
        /**
         * OwnedByResponse
         * @description GET .../item-instances/owned-by/{owner_entity_id} - deliberately not
         *     paginated (ADR 0020 / task brief): bounded by one owner's inventory.
         */
        OwnedByResponse: {
            /** Groups */
            groups: components["schemas"]["OwnedGroupOut"][];
        };
        /**
         * OwnedGroupOut
         * @description One container-group within the owned-by response - ADR 0020's "by
         *     owner, grouped" shape. `container` is the lightweight `EntitySummary`
         *     (not an `ItemOut`) since `containment.parent_entity_id` isn't
         *     restricted to item-tagged entities - the container itself might not be
         *     an item/item_instance at all (e.g. a room, a character).
         */
        OwnedGroupOut: {
            container: components["schemas"]["EntitySummary"] | null;
            /** Item Instances */
            item_instances: components["schemas"]["ItemInstanceOut"][];
        };
        /** Page[Annotated[Union[MembershipRosterEntryOut, PlayerRosterEntryOut, GmRosterEntryOut], FieldInfo(annotation=NoneType, required=True, discriminator='kind')]] */
        Page_Annotated_Union_MembershipRosterEntryOut__PlayerRosterEntryOut__GmRosterEntryOut___FieldInfo_annotation_NoneType__required_True__discriminator__kind____: {
            /** Items */
            items: (components["schemas"]["MembershipRosterEntryOut"] | components["schemas"]["PlayerRosterEntryOut"] | components["schemas"]["GmRosterEntryOut"])[];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[CampaignSummaryOut] */
        Page_CampaignSummaryOut_: {
            /** Items */
            items: components["schemas"]["CampaignSummaryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[CharacterSummaryOut] */
        Page_CharacterSummaryOut_: {
            /** Items */
            items: components["schemas"]["CharacterSummaryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[EntitySummary] */
        Page_EntitySummary_: {
            /** Items */
            items: components["schemas"]["EntitySummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ItemInstanceOut] */
        Page_ItemInstanceOut_: {
            /** Items */
            items: components["schemas"]["ItemInstanceOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ItemOut] */
        Page_ItemOut_: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[PlayerOut] */
        Page_PlayerOut_: {
            /** Items */
            items: components["schemas"]["PlayerOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[TenantSummaryOut] */
        Page_TenantSummaryOut_: {
            /** Items */
            items: components["schemas"]["TenantSummaryOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PayloadDescriptionOut */
        PayloadDescriptionOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "description";
            /** Content */
            content: string;
            /** Locale */
            locale: string;
        };
        /** PayloadDocumentOut */
        PayloadDocumentOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "document";
            /** Url */
            url: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
        };
        /** PayloadNumberOut */
        PayloadNumberOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Value */
            value: string;
        };
        /** PayloadPictureOut */
        PayloadPictureOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "picture";
            /** Url */
            url: string;
            /** File Type */
            file_type: string;
        };
        /**
         * PictureRefOut
         * @description A picture reference - a `url` pointing at the existing payload-content
         *     endpoint, plus `file_type`. `_picture_refs` below walks
         *     entity.information -> payloads -> picture directly rather than through
         *     an `EntityViewMixin` property (there never was one - checked, `pictures`
         *     would have needed the owning `Payload` row's own id to link through,
         *     not just its bytes, so it was never a fit here). Inlining raw picture
         *     bytes into a paginated list response (`GET /items` can return up to
         *     100 items per page) would make list responses balloon for anything
         *     with real images, and would be inconsistent with how the Entities
         *     endpoint represents the exact same underlying data
         *     (`schemas/payloads.py`'s `PayloadPictureOut`, also a `url`).
         */
        PictureRefOut: {
            /** Url */
            url: string;
            /** File Type */
            file_type: string;
        };
        /**
         * PlayerDetailOut
         * @description Identical shape to PlayerOut - Player has no columns the summary
         *     omits, unlike Entity's list/detail split (RFC 0004's own words). Kept
         *     as its own class anyway (rather than reusing PlayerOut as both list
         *     and detail response) since the RFC's endpoint table names it as its
         *     own schema, and a distinct name gives GET .../players/{id} its own
         *     OpenAPI schema rather than sharing one meant for a paginated list.
         */
        PlayerDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Characters */
            characters: components["schemas"]["CharacterSummaryOut"][];
        };
        /**
         * PlayerOut
         * @description Campaign roster shape (GET .../campaigns/{id}/players) - no
         *     tenant_id/campaign_id, already in the path.
         *
         *     RFC 0004's own shape also carries `created_by`/`updated_by` (ADR
         *     0029). Deliberately not included yet: `player.created_by`/`updated_by`
         *     don't land until user/player/character CRUD (ADR 0036/RFC 0007)
         *     actually writes to this table - matching the same deferral
         *     `schemas/tenants.py`'s roster entries make, for the same reason.
         */
        PlayerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Characters */
            characters: components["schemas"]["CharacterSummaryOut"][];
        };
        /**
         * PlayerRosterEntryOut
         * @description Sourced the same way `is_tenant_participant` (ADR 0030) already
         *     queries every Player row where Player.tenant_id matches - already
         *     denormalized, no join through Campaign needed.
         *
         *     Same attribution deferral as MembershipRosterEntryOut above -
         *     `player.created_by`/`updated_by` don't exist until ADR 0036/RFC 0007.
         */
        PlayerRosterEntryOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "player";
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /** Characters */
            characters: components["schemas"]["CharacterSummaryOut"][];
        };
        /**
         * PlayerSummaryOut
         * @description Used by GET /me (RFC 0004) - a bare Player row alone (just ids)
         *     wouldn't answer anything useful there; a caller needs to know not just
         *     which campaigns they're in but which characters they play there.
         *     Carries its own tenant_id/campaign_id explicitly, unlike PlayerOut
         *     below - /me spans every tenant, so there's no URL scoping to infer
         *     them from the way a campaign-nested route already has both in its
         *     path.
         *
         *     Requires `player.character_links` (each with `.character.being.entity`)
         *     eager-loaded first (`lazy="raise_on_sql"`, ADR 0018).
         */
        PlayerSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /**
             * Campaign Id
             * Format: uuid
             */
            campaign_id: string;
            /** Characters */
            characters: components["schemas"]["CharacterSummaryOut"][];
        };
        /**
         * TagValueOut
         * @description Wraps one entry of `EntityViewMixin.tags` (`list[tuple[str, bool | None]]`).
         */
        TagValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: boolean | null;
        };
        /**
         * TenantOut
         * @description GET /tenants/{id} - the full detail shape. No role here: the caller
         *     already knows they're at least a tenant-wide member, since
         *     get_tenant_context gates this route.
         */
        TenantOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
        };
        /**
         * TenantSummaryOut
         * @description One row of `GET /tenants` - every tenant the caller belongs to in
         *     any capacity. `role` is derived, not a plain column, so this needs an
         *     explicit constructor rather than `from_attributes=True` alone (ADR
         *     0020's own precedent for anything needing data beyond a bare ORM
         *     attribute copy). See ADR 0030/RFC 0003.
         */
        TenantSummaryOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /**
             * Role
             * @enum {string}
             */
            role: "owner" | "orga" | "participant";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * StatValueOut
         * @description A resolved stat value, keyed by its definition's name - see ADR 0020.
         *
         *     Reshaping, not a plain-column mapping, so built via a classmethod
         *     rather than from_attributes: which value_* column actually holds the
         *     value is chosen by reading StatDefinition.value_type first, not by
         *     probing all four columns for non-null (the DB's own CHECK constraint
         *     on entity_stat already guarantees exactly one is ever set).
         */
        lorenzo_api__schemas__entities__StatValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: number | string | boolean;
        };
        /**
         * StatValueOut
         * @description Wraps one entry of physical_stats/economic_stats/destroyable_stats/
         *     damaging_stats (each `list[tuple[str, int | None]]`).
         */
        lorenzo_api__schemas__items__StatValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** Problem */
        Problem: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            /** Problem detail */
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_tenants: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TenantSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_tenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_tenant_roster: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Annotated_Union_MembershipRosterEntryOut__PlayerRosterEntryOut__GmRosterEntryOut___FieldInfo_annotation_NoneType__required_True__discriminator__kind____"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_campaigns: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CampaignSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_campaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_players: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PlayerOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_player: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                campaign_id: string;
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_gms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                campaign_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GmOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_characters: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CharacterSummaryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    payload_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                payload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_entities: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EntitySummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_items: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_item_instances: {
        parameters: {
            query?: {
                /** @description Only return item instances contained in this entity. */
                container_id?: string | null;
                /** @description With container_id, also include instances nested arbitrarily deep inside it, not just its direct contents. */
                recursive?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ItemInstanceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_item_instances_owned_by: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                owner_entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnedByResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_item_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
