/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness: is the process up? No dependencies checked on purpose.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness: can we actually reach the database?
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Proves the whole token-verification pipeline end to end over real
         *     HTTP - see ADR 0023. Not nested under /tenants/{tenant_id}/... - this
         *     is about the caller's own identity across every tenant they belong to,
         *     not scoped to one.
         *
         *     Re-fetched with memberships eager-loaded rather than reusing the
         *     `user` CurrentUser resolved - that one only ever needs `.id` itself
         *     (get_tenant_context's Membership lookup), so eager-loading memberships
         *     on every authenticated request regardless of whether a route needs
         *     them would be wasted work.
         */
        get: operations["get_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/payloads/{payload_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Payload Content
         * @description Raw bytes for a picture/document payload, with the correct
         *     Content-Type - and Content-Disposition for documents - rather than
         *     embedding the bytes inline in a JSON response. See ADR 0020.
         *
         *     Same information_visibility check as GET /entities/{id} (ADR 0028's
         *     addendum) - a payload is only as visible as the Information it
         *     belongs to. "Doesn't exist," "wrong tenant," and "exists but you can't
         *     see its information" all raise the exact same PayloadNotFoundError,
         *     same body - matching get_tenant_context's own established precedent
         *     (ADR 0023) of not letting a caller distinguish "not found" from
         *     "found, but not for you."
         */
        get: operations["payload_content"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description A lightweight listing - EntitySummary rather than EntityDetailOut, to
         *     avoid an N+1-heavy response when listing many entities.
         */
        get: operations["list_entities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description The full detail shape, with every relationship eager-loaded up front.
         *
         *     Queried directly with the full .options() chain rather than delegating
         *     to dependencies.get_entity_or_404 first - that helper's plain
         *     session.get() wouldn't have any of these relationships loaded, so
         *     reusing it here would just mean a second, redundant round trip for
         *     this same row. The 404 check below covers exactly what that helper
         *     covers (missing id, or an id that belongs to a different tenant).
         */
        get: operations["get_entity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Items
         * @description Every base item type for this tenant - see ADR 0019/0020. Explicit
         *     tenant_id filter as defense in depth alongside RLS, not a replacement
         *     for it (ADR 0002/0021).
         */
        get: operations["list_items"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/items/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Item */
        get: operations["get_item"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Item Instances
         * @description Every item instance for this tenant, optionally filtered to one
         *     container's contents (?container_id=&recursive=). `recursive` defaults
         *     to false - the costlier, cycle-risk-bearing traversal is explicit
         *     opt-in, not the default (ADR 0020 / task brief) - consistent with
         *     owned-by-grouped below also being non-recursive by design. Filtering by
         *     container is an ordinary query-param filter on this same list, unlike
         *     the structurally-different owned-by grouping, which is its own
         *     endpoint (ADR 0020).
         */
        get: operations["list_item_instances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances/owned-by/{owner_entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Item Instances Owned By
         * @description Every item instance owned by owner_entity_id, grouped by *direct*
         *     container only (a None group for uncontained instances) - a one-level
         *     grouping, not a recursive container-tree walk. Deliberately not
         *     paginated - bounded by one owner's inventory (ADR 0020 / task brief).
         */
        get: operations["list_item_instances_owned_by"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/item-instances/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Item Instance
         * @description Not in the original task brief, added for REST symmetry with
         *     GET /items/{entity_id} - a resource with a list and filtered views but
         *     no direct single-item lookup by id would be a real gap.
         *
         *     Registered *after* /owned-by/{owner_entity_id} above - FastAPI/Starlette
         *     matches routes in registration order, and a wildcard path segment here
         *     would otherwise greedily match "owned-by" as an entity_id and shadow
         *     that route entirely. Confirmed empirically (not just reasoned through)
         *     that getting this order backwards really does break /owned-by/... with
         *     a 422, not just in theory.
         */
        get: operations["get_item_instance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DescriptionOut
         * @description Wraps one entry of `ItemViewMixin.descriptions` - see ADR 0020: the
         *     raw `tuple[str, str]` is a fine internal shape but a weak external JSON
         *     contract (no field names), so it's wrapped into a small named schema.
         */
        DescriptionOut: {
            /** Content */
            content: string;
            /** Locale */
            locale: string;
        };
        /**
         * EntityDetailOut
         * @description The full shape of a single entity - every relationship resolved and
         *     inlined. See ADR 0020. Deliberately not reused for the list endpoint,
         *     which returns EntitySummary instead to avoid an N+1-heavy response
         *     when listing many entities.
         */
        EntityDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Stats */
            stats: components["schemas"]["lorenzo_api__schemas__entities__StatValueOut"][];
            /** Stat Groups */
            stat_groups: components["schemas"]["EntitySummary"][];
            /** Information */
            information: components["schemas"]["InformationOut"][];
            /** Prototypes */
            prototypes: components["schemas"]["EntitySummary"][];
            /** Instances */
            instances: components["schemas"]["EntitySummary"][];
            parent: components["schemas"]["EntitySummary"] | null;
            /** Children */
            children: components["schemas"]["EntitySummary"][];
        };
        /**
         * EntitySummary
         * @description A lightweight entity reference - used anywhere an entity is pointed
         *     at generically (a container, a prototype, an owner) rather than fully
         *     described. See ADR 0020.
         */
        EntitySummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** RequestValidationError */
        HTTPValidationError: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            errors: components["schemas"]["ValidationError"][];
        };
        /**
         * InformationOut
         * @description A titled, categorized piece of information about an entity, with its
         *     payloads already resolved to their concrete kind - see ADR 0020. A
         *     single Information row's payloads can be of heterogeneous kinds, so
         *     each is resolved independently via payload_to_schema rather than
         *     assuming one kind per row.
         */
        InformationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Payloads */
            payloads: (components["schemas"]["PayloadDescriptionOut"] | components["schemas"]["PayloadNumberOut"] | components["schemas"]["PayloadPictureOut"] | components["schemas"]["PayloadDocumentOut"])[];
        };
        /**
         * ItemInstanceOut
         * @description A specific, ownable item ("My Shovel"), from `VItemInstance` -
         *     identical to `ItemOut` plus `owner_entity_id`. See ADR 0019/0020 and
         *     `ItemOut`'s docstring for the eager-load requirement.
         */
        ItemInstanceOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Owner Entity Id */
            owner_entity_id: string | null;
            /** Title */
            title: string | null;
            /** Weight */
            weight: number | null;
            /** Height */
            height: number | null;
            /** Price */
            price: number | null;
            /** Rarity */
            rarity: number | null;
            /** Hp */
            hp: number | null;
            /** Armor */
            armor: number | null;
            /** Container Entity Id */
            container_entity_id: string | null;
            /** Is Magical */
            is_magical: boolean | null;
            /** Is Cursed */
            is_cursed: boolean | null;
            /** Descriptions */
            descriptions: components["schemas"]["DescriptionOut"][];
            /** Pictures */
            pictures: components["schemas"]["PictureRefOut"][];
            /** Physical Stats */
            physical_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Economic Stats */
            economic_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Destroyable Stats */
            destroyable_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Damaging Stats */
            damaging_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Tags */
            tags: components["schemas"]["TagValueOut"][];
        };
        /**
         * ItemOut
         * @description A base item type ("Shovel"), from `VItem` - see ADR 0019/0020.
         *
         *     Constructing this requires the source `VItem` to already have its
         *     entity->information->payloads->description/picture,
         *     entity->information->knowledge_links (ADR 0028 - `descriptions` is
         *     visibility-gated, not a bare property anymore), and
         *     entity->stats->stat_definition->stat_group eager-loaded (see
         *     `routers.items.eager_load_options`, the exact recipe proven in
         *     `tests/test_v_item.py`) - the six wrapped properties/methods raise
         *     MissingGreenlet otherwise, they do not silently lazy-load.
         */
        ItemOut: {
            /**
             * Entity Id
             * Format: uuid
             */
            entity_id: string;
            /** Title */
            title: string | null;
            /** Weight */
            weight: number | null;
            /** Height */
            height: number | null;
            /** Price */
            price: number | null;
            /** Rarity */
            rarity: number | null;
            /** Hp */
            hp: number | null;
            /** Armor */
            armor: number | null;
            /** Container Entity Id */
            container_entity_id: string | null;
            /** Is Magical */
            is_magical: boolean | null;
            /** Is Cursed */
            is_cursed: boolean | null;
            /** Descriptions */
            descriptions: components["schemas"]["DescriptionOut"][];
            /** Pictures */
            pictures: components["schemas"]["PictureRefOut"][];
            /** Physical Stats */
            physical_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Economic Stats */
            economic_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Destroyable Stats */
            destroyable_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Damaging Stats */
            damaging_stats: components["schemas"]["lorenzo_api__schemas__items__StatValueOut"][];
            /** Tags */
            tags: components["schemas"]["TagValueOut"][];
        };
        /**
         * MeOut
         * @description The caller's own identity and tenant-wide memberships - see ADR 0023.
         *     Exists purely to prove the token-verification pipeline end to end over
         *     real HTTP, not the start of a fuller /users API.
         */
        MeOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Authgear Subject Id */
            authgear_subject_id: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipOut"][];
        };
        /**
         * MembershipOut
         * @description A tenant-wide administrative access grant - see ADR 0022/0023.
         */
        MembershipOut: {
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Role */
            role: string;
        };
        /**
         * OwnedByResponse
         * @description GET .../item-instances/owned-by/{owner_entity_id} - deliberately not
         *     paginated (ADR 0020 / task brief): bounded by one owner's inventory.
         */
        OwnedByResponse: {
            /** Groups */
            groups: components["schemas"]["OwnedGroupOut"][];
        };
        /**
         * OwnedGroupOut
         * @description One container-group within the owned-by response - ADR 0020's "by
         *     owner, grouped" shape. `container` is the lightweight `EntitySummary`
         *     (not an `ItemOut`) since `containment.parent_entity_id` isn't
         *     restricted to item-tagged entities - the container itself might not be
         *     an item/item_instance at all (e.g. a room, a character).
         */
        OwnedGroupOut: {
            container: components["schemas"]["EntitySummary"] | null;
            /** Item Instances */
            item_instances: components["schemas"]["ItemInstanceOut"][];
        };
        /** Page[EntitySummary] */
        Page_EntitySummary_: {
            /** Items */
            items: components["schemas"]["EntitySummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ItemInstanceOut] */
        Page_ItemInstanceOut_: {
            /** Items */
            items: components["schemas"]["ItemInstanceOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** Page[ItemOut] */
        Page_ItemOut_: {
            /** Items */
            items: components["schemas"]["ItemOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
        };
        /** PayloadDescriptionOut */
        PayloadDescriptionOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "description";
            /** Content */
            content: string;
            /** Locale */
            locale: string;
        };
        /** PayloadDocumentOut */
        PayloadDocumentOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "document";
            /** Url */
            url: string;
            /** Filename */
            filename: string;
            /** File Type */
            file_type: string;
        };
        /** PayloadNumberOut */
        PayloadNumberOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Value */
            value: string;
        };
        /** PayloadPictureOut */
        PayloadPictureOut: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "picture";
            /** Url */
            url: string;
            /** File Type */
            file_type: string;
        };
        /**
         * PictureRefOut
         * @description A picture reference - a `url` pointing at the existing payload-content
         *     endpoint, plus `file_type`. `_picture_refs` below walks
         *     entity.information -> payloads -> picture directly rather than through
         *     an `ItemViewMixin` property (there never was one - checked, `pictures`
         *     would have needed the owning `Payload` row's own id to link through,
         *     not just its bytes, so it was never a fit here). Inlining raw picture
         *     bytes into a paginated list response (`GET /items` can return up to
         *     100 items per page) would make list responses balloon for anything
         *     with real images, and would be inconsistent with how the Entities
         *     endpoint represents the exact same underlying data
         *     (`schemas/payloads.py`'s `PayloadPictureOut`, also a `url`).
         */
        PictureRefOut: {
            /** Url */
            url: string;
            /** File Type */
            file_type: string;
        };
        /**
         * TagValueOut
         * @description Wraps one entry of `ItemViewMixin.tags` (`list[tuple[str, bool | None]]`).
         */
        TagValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * StatValueOut
         * @description A resolved stat value, keyed by its definition's name - see ADR 0020.
         *
         *     Reshaping, not a plain-column mapping, so built via a classmethod
         *     rather than from_attributes: which value_* column actually holds the
         *     value is chosen by reading StatDefinition.value_type first, not by
         *     probing all four columns for non-null (the DB's own CHECK constraint
         *     on entity_stat already guarantees exactly one is ever set).
         */
        lorenzo_api__schemas__entities__StatValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: number | string | boolean;
        };
        /**
         * StatValueOut
         * @description Wraps one entry of physical_stats/economic_stats/destroyable_stats/
         *     damaging_stats (each `list[tuple[str, int | None]]`).
         */
        lorenzo_api__schemas__items__StatValueOut: {
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** Problem */
        Problem: {
            /** Problem title */
            title: string;
            /** Problem type */
            type: string;
            /** Status code */
            status: number;
            /** Problem detail */
            detail?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    payload_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                payload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_entities: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EntitySummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_entity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_items: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ItemOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_item: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_item_instances: {
        parameters: {
            query?: {
                /** @description Only return item instances contained in this entity. */
                container_id?: string | null;
                /** @description With container_id, also include instances nested arbitrarily deep inside it, not just its direct contents. */
                recursive?: boolean;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ItemInstanceOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    list_item_instances_owned_by: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                owner_entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnedByResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_item_instance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemInstanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Client Error */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "client-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 400,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Server Error */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "type": "server-error-type",
                     *       "title": "User facing error message.",
                     *       "status": 500,
                     *       "detail": "Additional error context."
                     *     }
                     */
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
