import type { Schema } from '@lorenzo/api-client';

export type { Page } from '@lorenzo/api-client';

export type MembershipOut = Schema<'MembershipOut'>;
export type CharacterSummaryOut = Schema<'CharacterSummaryOut'>;
export type PlayerContextOut = Schema<'PlayerContextOut'>;
export type MePlayerOut = Schema<'MePlayerOut'>;
export type BeingSummaryOut = Schema<'BeingSummaryOut'>;
export type CampaignSummaryOut = Schema<'CampaignSummaryOut'>;
export type TenantSummaryOut = Schema<'TenantSummaryOut'>;
export type MeOut = Schema<'MeOut'>;
export type ManagedScopeOut = Schema<'ManagedScopeOut'>;
export type ProfileUpdate = Schema<'ProfileUpdate'>;
export type Notification = Schema<'NotificationOut'>;
export type EntityChange = Schema<'EntityChangeOut'>;
export type CampaignOut = Schema<'CampaignOut'>;
export type CharacterCreate = Schema<'CharacterCreate'>;
export type CharacterUpdate = Schema<'CharacterUpdate'>;
export type CharacterOut = Schema<'CharacterOut'>;
export type UserRefOut = Schema<'UserRefOut'>;
export type PlayerCreate = Schema<'PlayerCreate'>;
export type PlayerSummaryOut = Schema<'PlayerSummaryOut'>;
export type CampaignCreate = Schema<'CampaignCreate'>;
export type CampaignUpdate = Schema<'CampaignUpdate'>;
export type GmOut = Schema<'GmOut'>;
export type TenantCreate = Schema<'TenantCreate'>;
export type MembershipRosterEntryOut = Schema<'MembershipRosterEntryOut'>;
export type PlayerRosterEntryOut = Schema<'PlayerRosterEntryOut'>;
export type GmRosterEntryOut = Schema<'GmRosterEntryOut'>;
export type MembershipCreate = Schema<'MembershipCreate'>;
export type MembershipUpdate = Schema<'MembershipUpdate'>;
export type ProblemOut = Schema<'ProblemOut'>;
export type BulkMembershipResultItem = Schema<'BulkMembershipResultItem'>;
export type AuditLogEntryOut = Schema<'AuditLogEntryOut'>;
export type NotificationCreate = Schema<'NotificationCreate'>;
export type TenantRole = TenantSummaryOut['role'];
export type RosterEntry = MembershipRosterEntryOut | PlayerRosterEntryOut | GmRosterEntryOut;
export type TenantOut = Schema<'TenantOut'>;
export type TenantUpdate = Schema<'TenantUpdate'>;
export type InviteCreate = Schema<'InviteCreate'>;
export type InviteCreatedOut = Schema<'InviteCreatedOut'>;
export type InviteOut = Schema<'InviteOut'>;
export type InvitePreviewOut = Schema<'InvitePreviewOut'>;
export type InviteRedeemOut = Schema<'InviteRedeemOut'>;
