import type { Schema } from '@lorenzo/api-client';

export type { Page } from '@lorenzo/api-client';

export type MembershipOut = Schema<'MembershipOut'>;
export type CharacterSummaryOut = Schema<'CharacterSummaryOut'>;
export type PlayerContextOut = Schema<'PlayerContextOut'>;
export type MePlayerOut = Schema<'MePlayerOut'>;
export type BeingSummaryOut = Schema<'BeingSummaryOut'>;
export type CampaignSummaryOut = Schema<'CampaignSummaryOut'>;
export type TenantSummaryOut = Schema<'TenantSummaryOut'>;
export type MeOut = Schema<'MeOut'>;
export type ManagedScopeOut = Schema<'ManagedScopeOut'>;
export type ProfileUpdate = Schema<'ProfileUpdate'>;
export type Notification = Schema<'NotificationOut'>;
export type EntityChange = Schema<'EntityChangeOut'>;
export type CampaignOut = Schema<'CampaignOut'>;
export type CharacterCreate = Schema<'CharacterCreate'>;
export type CharacterUpdate = Schema<'CharacterUpdate'>;
export type CharacterOut = Schema<'CharacterOut'>;
export type UserRefOut = Schema<'UserRefOut'>;
export type PlayerCreate = Schema<'PlayerCreate'>;
export type PlayerSummaryOut = Schema<'PlayerSummaryOut'>;
export type CampaignCreate = Schema<'CampaignCreate'>;
export type CampaignUpdate = Schema<'CampaignUpdate'>;
export type GmOut = Schema<'GmOut'>;
export type TenantCreate = Schema<'TenantCreate'>;
export type MembershipRosterEntryOut = Schema<'MembershipRosterEntryOut'>;
export type PlayerRosterEntryOut = Schema<'PlayerRosterEntryOut'>;
export type GmRosterEntryOut = Schema<'GmRosterEntryOut'>;
export type MembershipCreate = Schema<'MembershipCreate'>;
export type MembershipUpdate = Schema<'MembershipUpdate'>;
export type ProblemOut = Schema<'ProblemOut'>;
export type BulkMembershipResultItem = Schema<'BulkMembershipResultItem'>;
export type AuditLogEntryOut = Schema<'AuditLogEntryOut'>;
export type NotificationCreate = Schema<'NotificationCreate'>;
export type TenantRole = TenantSummaryOut['role'];
export type RosterEntry = MembershipRosterEntryOut | PlayerRosterEntryOut | GmRosterEntryOut;
export type TenantOut = Schema<'TenantOut'>;
export type TenantUpdate = Schema<'TenantUpdate'>;
export type InviteCreate = Schema<'InviteCreate'>;
export type InviteCreatedOut = Schema<'InviteCreatedOut'>;
export type InviteOut = Schema<'InviteOut'>;
export type InvitePreviewOut = Schema<'InvitePreviewOut'>;
export type InviteRedeemOut = Schema<'InviteRedeemOut'>;

// A library's repositories (RFC 0036, Shelf).
export type SubscriptionOut = Schema<'SubscriptionOut'>;
export type SubscriberOut = Schema<'SubscriberOut'>;
export type RepositorySummaryOut = Schema<'RepositorySummaryOut'>;
export type ContributionCountsOut = Schema<'ContributionCountsOut'>;
export type CopyPlanOut = Schema<'CopyPlanOut'>;
export type CopyStepOut = Schema<'CopyStepOut'>;
export type CopyOut = Schema<'CopyOut'>;
export type CopyRequest = Schema<'CopyRequest'>;
export type CollisionOut = Schema<'CollisionOut'>;
export type ResolutionIn = Schema<'ResolutionIn'>;
export type PreviousCopyOut = Schema<'PreviousCopyOut'>;

// A library's updates from a repository it copied (RFC 0036 S4).
export type UpdatesOut = Schema<'UpdatesOut'>;
export type RowChangeOut = Schema<'RowChangeOut'>;
export type FieldChangeOut = Schema<'FieldChangeOut'>;
export type RowRefOut = Schema<'RowRefOut'>;
export type AddedOut = Schema<'AddedOut'>;
export type AttachmentRefOut = Schema<'AttachmentRefOut'>;
export type AttachmentAddedOut = Schema<'AttachmentAddedOut'>;
export type ApplyUpdatesRequest = Schema<'ApplyUpdatesRequest'>;
export type ApplyUpdatesOut = Schema<'ApplyUpdatesOut'>;
export type UpdateActionIn = Schema<'UpdateActionIn'>;
export type AttachmentActionIn = Schema<'AttachmentActionIn'>;
export type NotAppliedOut = Schema<'NotAppliedOut'>;
export type RepositoryEntityOut = Schema<'RepositoryEntityOut'>;
export type RepositoryStatGroupOut = Schema<'RepositoryStatGroupOut'>;
export type RepositoryStatDefinitionOut = Schema<'RepositoryStatDefinitionOut'>;
