# generated by datamodel-codegen:
#   filename:  openapi.json

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, conint, constr


class Kind(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"


class State(StrEnum):
    released = "released"
    edited = "edited"


class AdminNotificationCreate(BaseModel):
    recipient_user_id: UUID = Field(..., title="Recipient User Id")
    type: str = Field(..., title="Type")
    title: str = Field(..., title="Title")
    body: str = Field(..., title="Body")


class AdminUserOut(BaseModel):
    id: UUID = Field(..., title="Id")
    email: str | None = Field(..., title="Email")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    pronouns: str | None = Field(..., title="Pronouns")
    bio: str | None = Field(..., title="Bio")
    locales: list[str] = Field(..., title="Locales")
    user_color: str | None = Field(..., title="User Color")
    suspended_at: AwareDatetime | None = Field(..., title="Suspended At")
    suspension_reason: str | None = Field(..., title="Suspension Reason")
    created_at: AwareDatetime = Field(..., title="Created At")


class AttachmentActionName(StrEnum):
    add = "add"
    detach = "detach"


class AttachmentCountsOut(BaseModel):
    added: int = Field(..., title="Added")
    removed: int = Field(..., title="Removed")


class AttachmentRefOut(BaseModel):
    child_source_id: UUID = Field(..., title="Child Source Id")
    child_local_id: UUID | None = Field(..., title="Child Local Id")
    child_name: str = Field(..., title="Child Name")
    parent_source_id: UUID = Field(..., title="Parent Source Id")
    parent_local_id: UUID | None = Field(..., title="Parent Local Id")
    parent_name: str = Field(..., title="Parent Name")


class AuditLogEntryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    actor_id: UUID | None = Field(..., title="Actor Id")
    action: str = Field(..., title="Action")
    target_type: str = Field(..., title="Target Type")
    target_id: UUID | None = Field(..., title="Target Id")
    detail: str | None = Field(..., title="Detail")
    created_at: AwareDatetime = Field(..., title="Created At")


class Kind1(StrEnum):
    item = "item"
    item_instance = "item_instance"
    being = "being"
    character = "character"


class BacklinkOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    kinds: list[Kind1] = Field(..., title="Kinds")
    information_id: UUID = Field(..., title="Information Id")
    title: str = Field(..., title="Title")
    type: str = Field(..., title="Type")


class BeingSummaryOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    is_pc: bool | None = Field(..., title="Is Pc")


class BodyUploadCampaignPicture(BaseModel):
    file: str = Field(
        ..., json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File"
    )


class BodyUploadMyPicture(BaseModel):
    file: str = Field(
        ..., json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File"
    )


class BodyUploadTenantPicture(BaseModel):
    file: str = Field(
        ..., json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File"
    )


class Reason(StrEnum):
    entity_removed = "entity_removed"
    stat_definition_removed = "stat_definition_removed"
    stat_definition_retyped = "stat_definition_retyped"
    stat_group_removed = "stat_group_removed"
    enum_value_removed = "enum_value_removed"
    kinds_changed = "kinds_changed"
    slug_changed = "slug_changed"
    attachment_added = "attachment_added"


class Kind2(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"
    attachment = "attachment"


class BreakingRowOut(BaseModel):
    kind: Kind2 = Field(..., title="Kind")
    row_id: UUID = Field(..., title="Row Id")
    parent_id: UUID | None = Field(..., title="Parent Id")
    name: str = Field(..., title="Name")
    reason: Reason = Field(..., title="Reason")
    detail: str = Field(..., title="Detail")


class BulkAddPrototypeRequest(BaseModel):
    prototype_id: UUID = Field(..., title="Prototype Id")
    item_ids: list[UUID] = Field(..., title="Item Ids")


class Status(StrEnum):
    ok = "ok"
    error = "error"


class BulkAssignItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    owner_character_id: UUID = Field(..., title="Owner Character Id")
    quantity: int | None = Field(None, title="Quantity")
    if_match: str | None = Field(None, title="If Match")
    move_to_owner: bool | None = Field(False, title="Move To Owner")
    with_contents: bool | None = Field(False, title="With Contents")
    override: bool | None = Field(False, title="Override")
    lift_binding: bool | None = Field(False, title="Lift Binding")


class BulkMoveItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    if_match: str | None = Field(None, title="If Match")


class BulkRemovePrototypeRequest(BaseModel):
    prototype_id: UUID = Field(..., title="Prototype Id")
    item_ids: list[UUID] = Field(..., title="Item Ids")


class BulkReparentPrototypeRequest(BaseModel):
    from_prototype_id: UUID = Field(..., title="From Prototype Id")
    to_prototype_id: UUID = Field(..., title="To Prototype Id")
    item_ids: list[UUID] | None = Field(None, title="Item Ids")


class CampaignCreate(BaseModel):
    name: str = Field(..., title="Name")
    game_system: str = Field(..., title="Game System")
    slug: str = Field(..., title="Slug")
    description: str = Field(..., title="Description")
    secret: bool | None = Field(False, title="Secret")


class CampaignOut(BaseModel):
    id: UUID = Field(..., title="Id")
    tenant_id: UUID = Field(..., title="Tenant Id")
    slug: str = Field(..., title="Slug")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    game_system: str = Field(..., title="Game System")
    secret: bool = Field(..., title="Secret")
    player_self_service: bool = Field(..., title="Player Self Service")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class CampaignSummaryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    slug: str = Field(..., title="Slug")
    name: str = Field(..., title="Name")
    game_system: str = Field(..., title="Game System")
    secret: bool = Field(..., title="Secret")


class CampaignUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    game_system: str | None = Field(None, title="Game System")
    slug: str | None = Field(None, title="Slug")
    description: str | None = Field(None, title="Description")
    secret: bool | None = Field(None, title="Secret")
    player_self_service: bool | None = Field(None, title="Player Self Service")


class CharacterCreate(BaseModel):
    name: str = Field(..., title="Name")
    owner_player_id: UUID | None = Field(None, title="Owner Player Id")
    player_ids: list[UUID] | None = Field([], title="Player Ids")


class CharacterPromote(BaseModel):
    owner_player_id: UUID | None = Field(None, title="Owner Player Id")


class CharacterSummaryOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    is_pc: bool = Field(..., title="Is Pc")


class CharacterUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    owner_player_id: UUID | None = Field(None, title="Owner Player Id")


class Kind3(StrEnum):
    stat_group = "stat_group"
    stat_definition = "stat_definition"
    slug = "slug"


class Choice(StrEnum):
    rename = "rename"
    merge = "merge"
    skip = "skip"


class CollisionOut(BaseModel):
    repository_id: UUID = Field(..., title="Repository Id")
    kind: Kind3 = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    name: str = Field(..., title="Name")
    local_id: UUID | None = Field(..., title="Local Id")
    choices: list[Choice] = Field(..., title="Choices")


class Comparator(StrEnum):
    lt = "lt"
    le = "le"
    eq = "eq"
    ne = "ne"
    ge = "ge"
    gt = "gt"


class ComparisonFormulaBodyInput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["comparison"] = Field("comparison", title="Kind")
    left_stat_definition_id: UUID = Field(..., title="Left Stat Definition Id")
    comparator: Comparator
    right_stat_definition_id: UUID | None = Field(None, title="Right Stat Definition Id")
    right_constant: float | constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        None, title="Right Constant"
    )
    true_value: str | None = Field(None, title="True Value")
    false_value: str | None = Field(None, title="False Value")


class ComparisonFormulaBodyOutput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["comparison"] = Field("comparison", title="Kind")
    left_stat_definition_id: UUID = Field(..., title="Left Stat Definition Id")
    comparator: Comparator
    right_stat_definition_id: UUID | None = Field(None, title="Right Stat Definition Id")
    right_constant: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        None, title="Right Constant"
    )
    true_value: str | None = Field(None, title="True Value")
    false_value: str | None = Field(None, title="False Value")


class Kind4(StrEnum):
    linear = "linear"
    comparison = "comparison"
    sum = "sum"
    contents = "contents"


class ComputedStatDependentOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    kind: Kind4 = Field(..., title="Kind")


class Source(StrEnum):
    computed = "computed"
    direct = "direct"
    unset = "unset"


class ContentsFormulaBody(BaseModel):
    kind: Literal["contents"] = Field("contents", title="Kind")
    source_stat_definition_id: UUID = Field(..., title="Source Stat Definition Id")


class Status6(StrEnum):
    ok = "ok"
    kept = "kept"


class ContributionCountsOut(BaseModel):
    entities: int = Field(..., title="Entities")
    stat_groups_copied: int = Field(..., title="Stat Groups Copied")
    stat_groups_merged: int = Field(..., title="Stat Groups Merged")
    stat_definitions_copied: int = Field(..., title="Stat Definitions Copied")
    stat_definitions_merged: int = Field(..., title="Stat Definitions Merged")
    attachments: int = Field(..., title="Attachments")


class Kind5(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"


class Mode(StrEnum):
    copied = "copied"
    merged = "merged"


class ContributionOut(BaseModel):
    kind: Kind5 = Field(..., title="Kind")
    local_id: UUID | None = Field(..., title="Local Id")
    source_id: UUID = Field(..., title="Source Id")
    name: str = Field(..., title="Name")
    mode: Mode | None = Field(..., title="Mode")


class Kind6(StrEnum):
    equipped = "equipped"
    not_carried = "not_carried"
    container = "container"
    read_only = "read_only"


class ContainerKind(StrEnum):
    being = "being"
    item_instance = "item_instance"
    other = "other"


class Again(StrEnum):
    keep = "keep"
    purge = "purge"


class DroppedOut(BaseModel):
    kind: str = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    reason: str = Field(..., title="Reason")


class DuplicateGroupRequest(BaseModel):
    name: str | None = Field(None, title="Name")


class EntityChangeOut(BaseModel):
    id: UUID = Field(..., title="Id")
    tenant_id: UUID = Field(..., title="Tenant Id")
    character_entity_id: UUID = Field(..., title="Character Entity Id")
    entity_id: UUID = Field(..., title="Entity Id")
    entity_name: str = Field(..., title="Entity Name")
    kind: str = Field(..., title="Kind")
    detail: str | None = Field(..., title="Detail")
    actor_user_id: UUID | None = Field(..., title="Actor User Id")
    occurred_at: AwareDatetime = Field(..., title="Occurred At")


class EntitySlugOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    slug: str = Field(..., title="Slug")


class EntitySlugUpdate(BaseModel):
    slug: constr(pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*$", max_length=100) = Field(..., title="Slug")


class EntityStatValueOut(BaseModel):
    name: str = Field(..., title="Name")
    value: int | str | float | bool = Field(..., title="Value")
    own: bool = Field(..., title="Own")


class EntitySummary(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    quantity: int | None = Field(None, title="Quantity")


class State3(StrEnum):
    clean = "clean"
    conflict = "conflict"
    not_applicable = "not_applicable"


class FieldChangeOut(BaseModel):
    field: str = Field(..., title="Field")
    label: str | None = Field(..., title="Label")
    state: State3 = Field(..., title="State")
    base: Any = Field(..., title="Base")
    upstream: Any = Field(..., title="Upstream")
    local: Any = Field(..., title="Local")
    added: list[Any] | None = Field(..., title="Added")
    removed: list[Any] | None = Field(..., title="Removed")


class GiveContentsRequest(BaseModel):
    owner_character_id: UUID = Field(..., title="Owner Character Id")
    recursive: bool | None = Field(True, title="Recursive")


class GivePackRequest(BaseModel):
    pack_id: UUID = Field(..., title="Pack Id")
    owner_entity_id: UUID = Field(..., title="Owner Entity Id")
    override: bool | None = Field(False, title="Override")


class GmOut(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")


class GmRosterEntryOut(BaseModel):
    kind: Literal["gm"] = Field("gm", title="Kind")
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")
    campaign_id: UUID = Field(..., title="Campaign Id")


class GroupCreate(BaseModel):
    name: str = Field(..., title="Name")
    member_character_ids: list[UUID] | None = Field([], title="Member Character Ids")


class Status7(StrEnum):
    ok = "ok"
    error = "error"


class GroupUpdate(BaseModel):
    name: str | None = Field(None, title="Name")


class InformationCreate(BaseModel):
    title: str = Field(..., title="Title")
    type: str = Field(..., title="Type")
    is_public: bool | None = Field(False, title="Is Public")
    content: str = Field(..., title="Content")
    locale: str | None = Field("en-US", title="Locale")
    order: int | None = Field(None, title="Order")


class InformationUpdate(BaseModel):
    title: str | None = Field(None, title="Title")
    type: str | None = Field(None, title="Type")
    is_public: bool | None = Field(None, title="Is Public")
    order: int | None = Field(None, title="Order")


class InviteRole(StrEnum):
    player = "player"
    gm = "gm"


class ItemCreate(BaseModel):
    name: str = Field(..., title="Name")
    prototype_ids: list[UUID] | None = Field([], title="Prototype Ids")
    in_public_catalog: bool | None = Field(False, title="In Public Catalog")
    slug: constr(pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*$", max_length=100) | None = Field(
        None, title="Slug"
    )


class ItemInstanceCreate(BaseModel):
    name: str | None = Field(None, title="Name")
    prototype_id: UUID = Field(..., title="Prototype Id")
    owner_character_id: UUID | None = Field(None, title="Owner Character Id")
    container_entity_id: UUID | None = Field(None, title="Container Entity Id")
    slug: constr(pattern=r"^[A-Za-z0-9][A-Za-z0-9_-]*$", max_length=100) | None = Field(
        None, title="Slug"
    )
    quantity: conint(ge=1) | None = Field(1, title="Quantity")
    override: bool | None = Field(False, title="Override")


class ItemInstanceUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    prototype_id: UUID | None = Field(None, title="Prototype Id")


class ItemUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    in_public_catalog: bool | None = Field(None, title="In Public Catalog")


class KindCountsOut(BaseModel):
    added: int = Field(..., title="Added")
    changed: int = Field(..., title="Changed")
    removed: int = Field(..., title="Removed")


class Kind7(StrEnum):
    entity = "entity"
    player = "player"


class KnowerOut(BaseModel):
    kind: Kind7 = Field(..., title="Kind")
    knower_entity_id: UUID | None = Field(None, title="Knower Entity Id")
    player_id: UUID | None = Field(None, title="Player Id")
    name: str | None = Field(..., title="Name")
    granted_at: AwareDatetime = Field(..., title="Granted At")


class KnowledgeEntryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    information_id: UUID = Field(..., title="Information Id")
    entity_id: UUID = Field(..., title="Entity Id")
    knower_entity_id: UUID | None = Field(..., title="Knower Entity Id")
    knower_player_id: UUID | None = Field(..., title="Knower Player Id")
    created_at: AwareDatetime = Field(..., title="Created At")


class ManagedCampaignOut(BaseModel):
    campaign_id: UUID = Field(..., title="Campaign Id")
    name: str = Field(..., title="Name")
    is_gm: bool = Field(..., title="Is Gm")


class Role(StrEnum):
    owner = "owner"
    orga = "orga"


class MeCapabilitiesOut(BaseModel):
    create_tenant: bool = Field(..., title="Create Tenant")


class MePlayerOut(BaseModel):
    id: UUID = Field(..., title="Id")
    tenant_id: UUID = Field(..., title="Tenant Id")
    campaign_id: UUID = Field(..., title="Campaign Id")
    characters: list[CharacterSummaryOut] = Field(..., title="Characters")
    self_service_effective: bool = Field(..., title="Self Service Effective")


class MembershipCreate(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    role: Role = Field(..., title="Role")


class MembershipOut(BaseModel):
    tenant_id: UUID = Field(..., title="Tenant Id")
    role: str = Field(..., title="Role")


class MembershipRosterEntryOut(BaseModel):
    kind: Literal["membership"] = Field("membership", title="Kind")
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")
    role: str = Field(..., title="Role")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")


class MembershipUpdate(BaseModel):
    role: Role = Field(..., title="Role")


class MergeItemInstanceRequest(BaseModel):
    into_entity_id: UUID = Field(..., title="Into Entity Id")


class NotAppliedOut(BaseModel):
    kind: str = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    field: str = Field(..., title="Field")
    reason: str = Field(..., title="Reason")
    name: str | None = Field(..., title="Name")
    label: str | None = Field(..., title="Label")


class NotificationCreate(BaseModel):
    recipient_user_id: UUID | None = Field(None, title="Recipient User Id")
    type: str = Field(..., title="Type")
    title: str = Field(..., title="Title")
    body: str = Field(..., title="Body")


class NotificationOut(BaseModel):
    id: UUID = Field(..., title="Id")
    batch_id: UUID = Field(..., title="Batch Id")
    user_id: UUID = Field(..., title="User Id")
    scope: str = Field(..., title="Scope")
    type: str = Field(..., title="Type")
    tenant_id: UUID | None = Field(..., title="Tenant Id")
    source_id: UUID | None = Field(..., title="Source Id")
    title: str = Field(..., title="Title")
    body: str = Field(..., title="Body")
    read_at: AwareDatetime | None = Field(..., title="Read At")
    created_at: AwareDatetime = Field(..., title="Created At")


class PageAdminUserOut(BaseModel):
    items: list[AdminUserOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageAttachmentRefOut(BaseModel):
    items: list[AttachmentRefOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageAuditLogEntryOut(BaseModel):
    items: list[AuditLogEntryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageBacklinkOut(BaseModel):
    items: list[BacklinkOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageBeingSummaryOut(BaseModel):
    items: list[BeingSummaryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageCampaignSummaryOut(BaseModel):
    items: list[CampaignSummaryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageCharacterSummaryOut(BaseModel):
    items: list[CharacterSummaryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageContributionOut(BaseModel):
    items: list[ContributionOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageEntityChangeOut(BaseModel):
    items: list[EntityChangeOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageEntitySummary(BaseModel):
    items: list[EntitySummary] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageKnowledgeEntryOut(BaseModel):
    items: list[KnowledgeEntryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageNotificationOut(BaseModel):
    items: list[NotificationOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PayloadDescriptionOut(BaseModel):
    id: UUID = Field(..., title="Id")
    order: int = Field(..., title="Order")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    kind: Literal["description"] = Field("description", title="Kind")
    content: str = Field(..., title="Content")
    locale: str = Field(..., title="Locale")


class PayloadDescriptionUpdate(BaseModel):
    content: str | None = Field(None, title="Content")
    locale: str | None = Field(None, title="Locale")


class PayloadDocumentOut(BaseModel):
    id: UUID = Field(..., title="Id")
    order: int = Field(..., title="Order")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    kind: Literal["document"] = Field("document", title="Kind")
    url: str = Field(..., title="Url")
    filename: str = Field(..., title="Filename")
    file_type: str = Field(..., title="File Type")


class PayloadNumberOut(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    id: UUID = Field(..., title="Id")
    order: int = Field(..., title="Order")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    kind: Literal["number"] = Field("number", title="Kind")
    value: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") = Field(..., title="Value")


class PayloadPictureOut(BaseModel):
    id: UUID = Field(..., title="Id")
    order: int = Field(..., title="Order")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    kind: Literal["picture"] = Field("picture", title="Kind")
    url: str = Field(..., title="Url")
    file_type: str = Field(..., title="File Type")


class PictureRefOut(BaseModel):
    url: str = Field(..., title="Url")
    file_type: str = Field(..., title="File Type")
    from_entity: EntitySummary | None


class PlayerContextOut(BaseModel):
    id: UUID = Field(..., title="Id")
    tenant_id: UUID = Field(..., title="Tenant Id")
    campaign_id: UUID = Field(..., title="Campaign Id")
    characters: list[CharacterSummaryOut] = Field(..., title="Characters")


class PlayerCreate(BaseModel):
    user_id: UUID = Field(..., title="User Id")


class PlayerOut(BaseModel):
    id: UUID = Field(..., title="Id")
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")
    characters: list[CharacterSummaryOut] = Field(..., title="Characters")
    self_service: bool | None = Field(..., title="Self Service")
    self_service_effective: bool = Field(..., title="Self Service Effective")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class PlayerRosterEntryOut(BaseModel):
    kind: Literal["player"] = Field("player", title="Kind")
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")
    campaign_id: UUID = Field(..., title="Campaign Id")
    characters: list[CharacterSummaryOut] = Field(..., title="Characters")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")


class PlayerSummaryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    user_id: UUID = Field(..., title="User Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    user_color: str | None = Field(..., title="User Color")
    characters: list[CharacterSummaryOut] = Field(..., title="Characters")
    self_service: bool | None = Field(..., title="Self Service")
    self_service_effective: bool = Field(..., title="Self Service Effective")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class PlayerUpdate(BaseModel):
    self_service: bool | None = Field(None, title="Self Service")


class PreviewInputOut(BaseModel):
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    name: str = Field(..., title="Name")
    value: int | float | str | bool | None = Field(..., title="Value")


class Mode1(StrEnum):
    keep = "keep"
    purge = "purge"


class PreviousCopyOut(BaseModel):
    mode: Mode1 = Field(..., title="Mode")
    entities: int = Field(..., title="Entities")
    stat_groups: int = Field(..., title="Stat Groups")
    stat_definitions: int = Field(..., title="Stat Definitions")
    also_removed: dict[str, int] = Field(..., title="Also Removed")


class ProblemOut(BaseModel):
    type: str = Field(..., title="Type")
    title: str = Field(..., title="Title")
    status: int = Field(..., title="Status")
    detail: str | None = Field(None, title="Detail")


class ProfileUpdate(BaseModel):
    nickname: constr(min_length=1) | None = Field(None, title="Nickname")
    display_name: str | None = Field(None, title="Display Name")
    pronouns: str | None = Field(None, title="Pronouns")
    bio: str | None = Field(None, title="Bio")
    locales: list[str] | None = Field(None, title="Locales")
    user_color: constr(pattern=r"^#[0-9A-Fa-f]{6}$") | None = Field(None, title="User Color")


class PrototypeAncestorOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    prototype_ids: list[UUID] = Field(..., title="Prototype Ids")


class PublishRequest(BaseModel):
    label: constr(min_length=1, max_length=80) | None = Field(None, title="Label")
    notes: constr(max_length=4000) | None = Field(None, title="Notes")
    breaking: bool | None = Field(False, title="Breaking")
    acknowledge_breaking: bool | None = Field(False, title="Acknowledge Breaking")


class ReleaseCountsOut(BaseModel):
    entities: KindCountsOut
    stat_groups: KindCountsOut
    stat_definitions: KindCountsOut
    attachments: AttachmentCountsOut
    descriptions_edited: int = Field(..., title="Descriptions Edited")


class ReleaseOut(BaseModel):
    id: UUID = Field(..., title="Id")
    number: int = Field(..., title="Number")
    label: str = Field(..., title="Label")
    notes: str | None = Field(..., title="Notes")
    breaking: bool = Field(..., title="Breaking")
    created_at: AwareDatetime = Field(..., title="Created At")
    digest: str | None = Field(..., title="Digest")
    counts: ReleaseCountsOut | None
    breaking_rows: list[BreakingRowOut] = Field(..., title="Breaking Rows")


class ReleaseRefOut(BaseModel):
    id: UUID = Field(..., title="Id")
    number: int = Field(..., title="Number")
    label: str = Field(..., title="Label")


class ReleaseUpdate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    label: constr(min_length=1, max_length=80) | None = Field(None, title="Label")
    notes: constr(max_length=4000) | None = Field(None, title="Notes")


class RepositoryDependencyOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    slug: str = Field(..., title="Slug")
    invited: bool = Field(..., title="Invited")
    copied: bool = Field(..., title="Copied")
    published: bool = Field(..., title="Published")


class Kind8(StrEnum):
    item = "item"
    item_instance = "item_instance"
    being = "being"
    character = "character"


class RepositoryEntityOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    kinds: list[Kind8] = Field(..., title="Kinds")
    prototype_ids: list[UUID] = Field(..., title="Prototype Ids")


class RepositorySummaryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    slug: str = Field(..., title="Slug")
    description: str = Field(..., title="Description")
    published_at: AwareDatetime | None = Field(..., title="Published At")


class Kind9(StrEnum):
    stat_group = "stat_group"
    stat_definition = "stat_definition"
    slug = "slug"


class Action(StrEnum):
    rename = "rename"
    merge = "merge"
    skip = "skip"


class ResolutionIn(BaseModel):
    kind: Kind9 = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    action: Action = Field(..., title="Action")
    name: str | None = Field(None, title="Name")


class Kind10(StrEnum):
    item = "item"
    item_instance = "item_instance"
    being = "being"
    character = "character"


class ResolvedSlugOut(BaseModel):
    slug: str = Field(..., title="Slug")
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    kinds: list[Kind10] = Field(..., title="Kinds")


class RoundMode(StrEnum):
    none = "none"
    floor = "floor"
    ceil = "ceil"
    round = "round"
    truncate = "truncate"


class Kind11(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"


class State4(StrEnum):
    released = "released"
    edited = "edited"


class Kind12(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"
    attachment = "attachment"


class RowNameOut(BaseModel):
    kind: Kind12 = Field(..., title="Kind")
    row_id: UUID = Field(..., title="Row Id")
    parent_id: UUID | None = Field(..., title="Parent Id")
    name: str = Field(..., title="Name")
    parent_name: str | None = Field(..., title="Parent Name")


class Kind13(StrEnum):
    entity = "entity"
    stat_group = "stat_group"
    stat_definition = "stat_definition"


class SetContainerRequest(BaseModel):
    container_entity_id: UUID = Field(..., title="Container Entity Id")
    override: bool | None = Field(False, title="Override")
    lift_binding: bool | None = Field(False, title="Lift Binding")
    merge_identical: bool | None = Field(False, title="Merge Identical")


class SetEntityStatRequest(BaseModel):
    value: int | str | float | bool = Field(..., title="Value")
    acquire_group: bool | None = Field(False, title="Acquire Group")


class SetOwnerRequest(BaseModel):
    owner_character_id: UUID = Field(..., title="Owner Character Id")
    move_to_owner: bool | None = Field(False, title="Move To Owner")
    override: bool | None = Field(False, title="Override")
    lift_binding: bool | None = Field(False, title="Lift Binding")


class SetPrototypesRequest(BaseModel):
    prototype_ids: list[UUID] | None = Field([], title="Prototype Ids")


class SplitItemInstanceRequest(BaseModel):
    quantity: int = Field(..., title="Quantity")
    owner_character_id: UUID | None = Field(None, title="Owner Character Id")


class StatEnumValueCreate(BaseModel):
    value: str = Field(..., title="Value")
    sort_order: int | None = Field(None, title="Sort Order")


class StatGroupCreate(BaseModel):
    name: str = Field(..., title="Name")
    priority: int | None = Field(0, title="Priority")
    mandatory: bool | None = Field(False, title="Mandatory")


class StatGroupOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    priority: int = Field(..., title="Priority")
    mandatory: bool = Field(..., title="Mandatory")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class StatValueOut(BaseModel):
    name: str = Field(..., title="Name")
    value: int | float | None = Field(..., title="Value")


class StatValueType(StrEnum):
    int = "int"
    text = "text"
    float = "float"
    bool = "bool"
    enum = "enum"


class SubscriberOut(BaseModel):
    tenant_id: UUID = Field(..., title="Tenant Id")
    name: str = Field(..., title="Name")
    slug: str = Field(..., title="Slug")
    granted_at: AwareDatetime | None = Field(..., title="Granted At")
    granted_by: UUID | None = Field(..., title="Granted By")
    copied_at: AwareDatetime | None = Field(..., title="Copied At")
    synced_at: AwareDatetime | None = Field(..., title="Synced At")
    synced_release: ReleaseRefOut | None


class SubscriptionOut(BaseModel):
    repository: RepositorySummaryOut
    granted_at: AwareDatetime | None = Field(..., title="Granted At")
    copied_at: AwareDatetime | None = Field(..., title="Copied At")
    synced_at: AwareDatetime | None = Field(..., title="Synced At")
    contributed: ContributionCountsOut | None
    synced_release: ReleaseRefOut | None
    current_release: ReleaseRefOut | None


class SumTermBodyInput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    coefficient: float | constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        "1", title="Coefficient"
    )


class SumTermBodyOutput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    coefficient: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        "1", title="Coefficient"
    )


class SuspendUserRequest(BaseModel):
    reason: str | None = Field(None, title="Reason")


class TagValueOut(BaseModel):
    name: str = Field(..., title="Name")
    value: bool | None = Field(..., title="Value")


class TenantKind(StrEnum):
    play = "play"
    repository = "repository"


class TenantOut(BaseModel):
    id: UUID = Field(..., title="Id")
    slug: str = Field(..., title="Slug")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    kind: TenantKind
    published_at: AwareDatetime | None = Field(..., title="Published At")
    npcs_shared_with_gms: bool = Field(
        ...,
        description="Whether every GM of the library reads the GM-only text of the entries no campaign owns: the beings that are in no campaign, and what a copy of a repository brought, such as its catalog items. On (the default), every GM reads them; off, only the GMs who wrote an entry, or who share a campaign with whoever did, read it. An entry a campaign owns, because one of its characters holds it or stands in it, is read only by that campaign's GMs either way. Owners and Organizers read everything.",
        title="Npcs Shared With Gms",
    )
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")


class Role3(StrEnum):
    owner = "owner"
    orga = "orga"
    participant = "participant"


class TenantSummaryOut(BaseModel):
    id: UUID = Field(..., title="Id")
    slug: str = Field(..., title="Slug")
    name: str = Field(..., title="Name")
    role: Role3 = Field(..., title="Role")
    kind: TenantKind


class TenantUpdate(BaseModel):
    name: str | None = Field(None, title="Name")
    slug: constr(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$") | None = Field(None, title="Slug")
    description: str | None = Field(None, title="Description")
    npcs_shared_with_gms: bool | None = Field(
        None,
        description="Whether every GM of the library reads the GM-only text of the entries no campaign owns: the beings that are in no campaign, and what a copy of a repository brought, such as its catalog items. On (the default), every GM reads them; off, only the GMs who wrote an entry, or who share a campaign with whoever did, read it. An entry a campaign owns, because one of its characters holds it or stands in it, is read only by that campaign's GMs either way. Owners and Organizers read everything.",
        title="Npcs Shared With Gms",
    )


class Action1(StrEnum):
    apply = "apply"
    add = "add"
    detach = "detach"


class Action2(StrEnum):
    rename = "rename"
    merge = "merge"
    skip = "skip"


class UpdateResolutionIn(BaseModel):
    action: Action2 = Field(..., title="Action")
    name: str | None = Field(None, title="Name")


class UserRefOut(BaseModel):
    id: UUID = Field(..., title="Id")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")
    input: Any | None = Field(None, title="Input")
    ctx: dict[str, Any] | None = Field(None, title="Context")


class Problem(BaseModel):
    title: str = Field(..., title="Problem title")
    type: str = Field(..., title="Problem type")
    status: int = Field(..., title="Status code")
    detail: str | None = Field(None, title="Problem detail")


class ApplyUpdatesOut(BaseModel):
    dry_run: bool = Field(..., title="Dry Run")
    applied: int = Field(..., title="Applied")
    added: int = Field(..., title="Added")
    detached: int = Field(..., title="Detached")
    attachments_added: int = Field(..., title="Attachments Added")
    attachments_detached: int = Field(..., title="Attachments Detached")
    not_applied: list[NotAppliedOut] = Field(..., title="Not Applied")


class AttachmentActionIn(BaseModel):
    child_source_id: UUID = Field(..., title="Child Source Id")
    parent_source_id: UUID = Field(..., title="Parent Source Id")
    action: AttachmentActionName
    confirm: bool | None = Field(None, title="Confirm")


class BreakingNoteOut(BaseModel):
    reason: Reason = Field(..., title="Reason")
    detail: str = Field(..., title="Detail")
    release: ReleaseRefOut


class BulkMembershipResultItem(BaseModel):
    user_id: UUID = Field(..., title="User Id")
    status: Status = Field(..., title="Status")
    membership: MembershipRosterEntryOut | None = None
    problem: ProblemOut | None = None


class BulkMoveContainerRequest(BaseModel):
    to_container_entity_id: UUID = Field(..., title="To Container Entity Id")
    from_container_entity_id: UUID | None = Field(None, title="From Container Entity Id")
    items: list[BulkMoveItem] | None = Field(None, title="Items")
    override: bool | None = Field(False, title="Override")
    lift_binding: bool | None = Field(False, title="Lift Binding")
    merge_identical: bool | None = Field(False, title="Merge Identical")


class CharacterOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    name: str = Field(..., title="Name")
    is_pc: bool = Field(..., title="Is Pc")
    owner_player_id: UUID | None = Field(..., title="Owner Player Id")
    players: list[PlayerContextOut] = Field(..., title="Players")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")


class ComputedStatPreviewOut(BaseModel):
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    value: int | float | str | bool | None = Field(..., title="Value")
    source: Source = Field(..., title="Source")
    inputs: list[PreviewInputOut] = Field(..., title="Inputs")


class ContentsResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    title: str = Field(..., title="Title")
    status: Status6 = Field(..., title="Status")
    owner: EntitySummary | None = None
    problem: ProblemOut | None = None


class CopyRequest(BaseModel):
    resolutions: list[ResolutionIn] | None = Field(None, title="Resolutions")
    dry_run: bool | None = Field(None, title="Dry Run")
    again: Again | None = Field(None, title="Again")


class CopyStepOut(BaseModel):
    repository_id: UUID = Field(..., title="Repository Id")
    name: str = Field(..., title="Name")
    granted: bool = Field(..., title="Granted")
    published: bool = Field(..., title="Published")
    already_copied: bool = Field(..., title="Already Copied")
    entities: int = Field(..., title="Entities")
    stat_groups: int = Field(..., title="Stat Groups")
    stat_definitions: int = Field(..., title="Stat Definitions")
    information: int = Field(..., title="Information")
    attachments: int = Field(..., title="Attachments")
    dropped: list[DroppedOut] = Field(..., title="Dropped")


class DescriptionOut(BaseModel):
    content: str = Field(..., title="Content")
    locale: str = Field(..., title="Locale")
    from_entity: EntitySummary | None


class GroupMemberResultItem(BaseModel):
    character_entity_id: UUID = Field(..., title="Character Entity Id")
    status: Status7 = Field(..., title="Status")
    problem: ProblemOut | None = None


class HTTPValidationError(BaseModel):
    title: str = Field(..., title="Problem title")
    type: str = Field(..., title="Problem type")
    status: int = Field(..., title="Status code")
    errors: list[ValidationError]


class Payloads(
    RootModel[PayloadDescriptionOut | PayloadNumberOut | PayloadPictureOut | PayloadDocumentOut]
):
    root: PayloadDescriptionOut | PayloadNumberOut | PayloadPictureOut | PayloadDocumentOut = Field(
        ..., discriminator="kind"
    )


class InformationOut(BaseModel):
    id: UUID = Field(..., title="Id")
    title: str = Field(..., title="Title")
    type: str = Field(..., title="Type")
    is_public: bool = Field(..., title="Is Public")
    order: int = Field(..., title="Order")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    payloads: list[Payloads] = Field(..., title="Payloads")


class InviteCreate(BaseModel):
    expires_at: AwareDatetime = Field(..., title="Expires At")
    max_uses: conint(ge=1) | None = Field(None, title="Max Uses")
    role: InviteRole | None = "player"


class InviteCreatedOut(BaseModel):
    id: UUID = Field(..., title="Id")
    campaign_id: UUID = Field(..., title="Campaign Id")
    role: InviteRole
    created_by: UUID | None = Field(..., title="Created By")
    created_at: AwareDatetime = Field(..., title="Created At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    max_uses: int | None = Field(..., title="Max Uses")
    use_count: int = Field(..., title="Use Count")
    revoked_at: AwareDatetime | None = Field(..., title="Revoked At")
    is_active: bool = Field(..., title="Is Active")
    token: str = Field(..., title="Token")


class InviteOut(BaseModel):
    id: UUID = Field(..., title="Id")
    campaign_id: UUID = Field(..., title="Campaign Id")
    role: InviteRole
    created_by: UUID | None = Field(..., title="Created By")
    created_at: AwareDatetime = Field(..., title="Created At")
    expires_at: AwareDatetime = Field(..., title="Expires At")
    max_uses: int | None = Field(..., title="Max Uses")
    use_count: int = Field(..., title="Use Count")
    revoked_at: AwareDatetime | None = Field(..., title="Revoked At")
    is_active: bool = Field(..., title="Is Active")


class InvitePreviewOut(BaseModel):
    campaign_name: str = Field(..., title="Campaign Name")
    picture_url: str | None = Field(..., title="Picture Url")
    role: InviteRole


class InviteRedeemOut(BaseModel):
    tenant_id: UUID = Field(..., title="Tenant Id")
    campaign_id: UUID = Field(..., title="Campaign Id")
    role: InviteRole
    player_id: UUID | None = Field(..., title="Player Id")
    already_joined: bool = Field(..., title="Already Joined")


class ItemInstanceOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    title: str = Field(..., title="Title")
    weight: int | float | None = Field(..., title="Weight")
    height: int | float | None = Field(..., title="Height")
    price: int | float | None = Field(..., title="Price")
    rarity: int | float | None = Field(..., title="Rarity")
    hp: int | float | None = Field(..., title="Hp")
    armor: int | float | None = Field(..., title="Armor")
    container_entity_id: UUID | None = Field(..., title="Container Entity Id")
    quantity: int | None = Field(..., title="Quantity")
    prototype_ids: list[UUID] = Field(..., title="Prototype Ids")
    is_container: bool | None = Field(..., title="Is Container")
    descriptions: list[DescriptionOut] = Field(..., title="Descriptions")
    pictures: list[PictureRefOut] = Field(..., title="Pictures")
    physical_stats: list[StatValueOut] = Field(..., title="Physical Stats")
    economic_stats: list[StatValueOut] = Field(..., title="Economic Stats")
    destroyable_stats: list[StatValueOut] = Field(..., title="Destroyable Stats")
    damaging_stats: list[StatValueOut] = Field(..., title="Damaging Stats")
    tags: list[TagValueOut] = Field(..., title="Tags")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    owner_entity_id: UUID | None = Field(..., title="Owner Entity Id")
    slug: str | None = Field(..., title="Slug")
    bound: bool = Field(..., title="Bound")


class ItemOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    title: str = Field(..., title="Title")
    weight: int | float | None = Field(..., title="Weight")
    height: int | float | None = Field(..., title="Height")
    price: int | float | None = Field(..., title="Price")
    rarity: int | float | None = Field(..., title="Rarity")
    hp: int | float | None = Field(..., title="Hp")
    armor: int | float | None = Field(..., title="Armor")
    container_entity_id: UUID | None = Field(..., title="Container Entity Id")
    quantity: int | None = Field(..., title="Quantity")
    prototype_ids: list[UUID] = Field(..., title="Prototype Ids")
    is_container: bool | None = Field(..., title="Is Container")
    descriptions: list[DescriptionOut] = Field(..., title="Descriptions")
    pictures: list[PictureRefOut] = Field(..., title="Pictures")
    physical_stats: list[StatValueOut] = Field(..., title="Physical Stats")
    economic_stats: list[StatValueOut] = Field(..., title="Economic Stats")
    destroyable_stats: list[StatValueOut] = Field(..., title="Destroyable Stats")
    damaging_stats: list[StatValueOut] = Field(..., title="Damaging Stats")
    tags: list[TagValueOut] = Field(..., title="Tags")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    in_public_catalog: bool = Field(..., title="In Public Catalog")


class LinearFormulaBodyInput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["linear"] = Field("linear", title="Kind")
    source_stat_definition_id: UUID = Field(..., title="Source Stat Definition Id")
    multiplier: float | constr(
        pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$"
    ) = Field(..., title="Multiplier")
    offset: float | constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        "0", title="Offset"
    )
    round_mode: RoundMode | None = "none"


class LinearFormulaBodyOutput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["linear"] = Field("linear", title="Kind")
    source_stat_definition_id: UUID = Field(..., title="Source Stat Definition Id")
    multiplier: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") = Field(..., title="Multiplier")
    offset: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field("0", title="Offset")
    round_mode: RoundMode | None = "none"


class ManagedTenantOut(BaseModel):
    tenant_id: UUID = Field(..., title="Tenant Id")
    name: str = Field(..., title="Name")
    slug: str = Field(..., title="Slug")
    role: Role | None = Field(..., title="Role")
    kind: TenantKind
    campaigns: list[ManagedCampaignOut] = Field(..., title="Campaigns")


class MeOut(BaseModel):
    id: UUID = Field(..., title="Id")
    authgear_subject_id: str = Field(..., title="Authgear Subject Id")
    email: str | None = Field(..., title="Email")
    nickname: str | None = Field(..., title="Nickname")
    display_name: str | None = Field(..., title="Display Name")
    pronouns: str | None = Field(..., title="Pronouns")
    bio: str | None = Field(..., title="Bio")
    locales: list[str] = Field(..., title="Locales")
    user_color: str | None = Field(..., title="User Color")
    picture_url: str = Field(..., title="Picture Url")
    memberships: list[MembershipOut] = Field(..., title="Memberships")
    players: list[MePlayerOut] = Field(..., title="Players")
    campaign_gm_grants: list[CampaignSummaryOut] = Field(..., title="Campaign Gm Grants")
    capabilities: MeCapabilitiesOut


class OwnedGroupOut(BaseModel):
    container: EntitySummary | None
    item_instances: list[ItemInstanceOut] = Field(..., title="Item Instances")


class PackItemOut(BaseModel):
    item_instance: ItemInstanceOut
    children: list[PackItemOut] = Field(..., title="Children")


class Items(RootModel[MembershipRosterEntryOut | PlayerRosterEntryOut | GmRosterEntryOut]):
    root: MembershipRosterEntryOut | PlayerRosterEntryOut | GmRosterEntryOut = Field(
        ..., discriminator="kind"
    )


class PageAnnotatedUnionMembershipRosterEntryOutPlayerRosterEntryOutGmRosterEntryOutFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorKind(
    BaseModel
):
    items: list[Items] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageInformationOut(BaseModel):
    items: list[InformationOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageInviteOut(BaseModel):
    items: list[InviteOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageItemInstanceOut(BaseModel):
    items: list[ItemInstanceOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageItemOut(BaseModel):
    items: list[ItemOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PagePlayerSummaryOut(BaseModel):
    items: list[PlayerSummaryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageReleaseOut(BaseModel):
    items: list[ReleaseOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageRepositoryEntityOut(BaseModel):
    items: list[RepositoryEntityOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageStatGroupOut(BaseModel):
    items: list[StatGroupOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageSubscriberOut(BaseModel):
    items: list[SubscriberOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageSubscriptionOut(BaseModel):
    items: list[SubscriptionOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageTenantOut(BaseModel):
    items: list[TenantOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageTenantSummaryOut(BaseModel):
    items: list[TenantSummaryOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class ReleaseAuthoredOut(BaseModel):
    id: UUID = Field(..., title="Id")
    number: int = Field(..., title="Number")
    label: str = Field(..., title="Label")
    notes: str | None = Field(..., title="Notes")
    breaking: bool = Field(..., title="Breaking")
    created_at: AwareDatetime = Field(..., title="Created At")
    digest: str | None = Field(..., title="Digest")
    counts: ReleaseCountsOut | None
    breaking_rows: list[BreakingRowOut] = Field(..., title="Breaking Rows")
    created_by: UUID | None = Field(..., title="Created By")


class ReleasePreviewOut(BaseModel):
    release: ReleaseOut | None
    baseline: bool = Field(..., title="Baseline")
    matches: bool | None = Field(..., title="Matches")
    live_digest: str = Field(..., title="Live Digest")
    differing_rows: int = Field(..., title="Differing Rows")
    counts: ReleaseCountsOut
    added: list[RowNameOut] = Field(..., title="Added")
    changed: list[RowNameOut] = Field(..., title="Changed")
    removed: list[RowNameOut] = Field(..., title="Removed")
    breaking: list[BreakingRowOut] = Field(..., title="Breaking")
    descriptions_edited: int | None = Field(..., title="Descriptions Edited")
    libraries_told: int = Field(..., title="Libraries Told")


class RepositoryStatDefinitionOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    value_type: StatValueType
    enum_values: list[str] = Field(..., title="Enum Values")


class RepositoryStatGroupOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    priority: int = Field(..., title="Priority")
    mandatory: bool = Field(..., title="Mandatory")
    definitions: list[RepositoryStatDefinitionOut] = Field(..., title="Definitions")


class RowChangeOut(BaseModel):
    kind: Kind11 = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    local_id: UUID = Field(..., title="Local Id")
    name: str = Field(..., title="Name")
    fields: list[FieldChangeOut] = Field(..., title="Fields")
    state: State4 | None = Field(..., title="State")
    breaking: list[BreakingNoteOut] = Field(..., title="Breaking")


class RowRefOut(BaseModel):
    kind: Kind13 = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    local_id: UUID | None = Field(..., title="Local Id")
    name: str = Field(..., title="Name")
    state: State4 | None = Field(..., title="State")
    breaking: list[BreakingNoteOut] = Field(..., title="Breaking")


class StatDefinitionCreate(BaseModel):
    name: str = Field(..., title="Name")
    stat_group_id: UUID = Field(..., title="Stat Group Id")
    value_type: StatValueType
    enum_values: list[str] | None = Field(None, title="Enum Values")


class StatDefinitionOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    stat_group_id: UUID = Field(..., title="Stat Group Id")
    value_type: StatValueType
    enum_values: list[str] = Field(..., title="Enum Values")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class SumFormulaBodyInput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["sum"] = Field("sum", title="Kind")
    terms: list[SumTermBodyInput] = Field(..., max_length=20, min_length=1, title="Terms")
    offset: float | constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field(
        "0", title="Offset"
    )
    round_mode: RoundMode | None = "none"


class SumFormulaBodyOutput(BaseModel):
    model_config = ConfigDict(
        regex_engine="python-re",
    )
    kind: Literal["sum"] = Field("sum", title="Kind")
    terms: list[SumTermBodyOutput] = Field(..., max_length=20, min_length=1, title="Terms")
    offset: constr(pattern=r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$") | None = Field("0", title="Offset")
    round_mode: RoundMode | None = "none"


class TenantCreate(BaseModel):
    name: str = Field(..., title="Name")
    slug: constr(pattern=r"^[a-z0-9]+(-[a-z0-9]+)*$") | None = Field(None, title="Slug")
    description: str | None = Field(None, title="Description")
    kind: TenantKind | None = None


class UpdateActionIn(BaseModel):
    kind: Kind13 = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    action: Action1 = Field(..., title="Action")
    keep_local: list[str] | None = Field(None, title="Keep Local")
    take_upstream: list[str] | None = Field(None, title="Take Upstream")
    resolution: UpdateResolutionIn | None = None
    confirm: bool | None = Field(None, title="Confirm")


class AddedOut(BaseModel):
    kind: Kind = Field(..., title="Kind")
    source_id: UUID = Field(..., title="Source Id")
    name: str = Field(..., title="Name")
    collision: CollisionOut | None
    state: State | None = Field(..., title="State")
    breaking: list[BreakingNoteOut] = Field(..., title="Breaking")


class ApplyUpdatesRequest(BaseModel):
    actions: list[UpdateActionIn] = Field(..., title="Actions")
    attachments: list[AttachmentActionIn] | None = Field(None, title="Attachments")
    dry_run: bool | None = Field(None, title="Dry Run")


class AttachmentAddedOut(BaseModel):
    child_source_id: UUID = Field(..., title="Child Source Id")
    child_local_id: UUID | None = Field(..., title="Child Local Id")
    child_name: str = Field(..., title="Child Name")
    parent_source_id: UUID = Field(..., title="Parent Source Id")
    parent_local_id: UUID | None = Field(..., title="Parent Local Id")
    parent_name: str = Field(..., title="Parent Name")
    state: State | None = Field(..., title="State")
    breaking: list[BreakingNoteOut] = Field(..., title="Breaking")
    applicable: bool = Field(..., title="Applicable")
    reason: str | None = Field(..., title="Reason")


class AttachmentChangeOut(BaseModel):
    child_source_id: UUID = Field(..., title="Child Source Id")
    child_local_id: UUID | None = Field(..., title="Child Local Id")
    child_name: str = Field(..., title="Child Name")
    parent_source_id: UUID = Field(..., title="Parent Source Id")
    parent_local_id: UUID | None = Field(..., title="Parent Local Id")
    parent_name: str = Field(..., title="Parent Name")
    state: State | None = Field(..., title="State")
    breaking: list[BreakingNoteOut] = Field(..., title="Breaking")


class BulkAddPrototypeResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    status: Status = Field(..., title="Status")
    item: ItemOut | None = None
    problem: ProblemOut | None = None


class BulkAssignResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    status: Status = Field(..., title="Status")
    item_instance: ItemInstanceOut | None = None
    problem: ProblemOut | None = None
    contents: list[ContentsResultItem] | None = Field([], title="Contents", validate_default=True)


class BulkMoveResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    status: Status = Field(..., title="Status")
    item_instance: ItemInstanceOut | None = None
    problem: ProblemOut | None = None


class BulkRemovePrototypeResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    status: Status = Field(..., title="Status")
    item: ItemOut | None = None
    problem: ProblemOut | None = None


class BulkReparentResultItem(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    status: Status = Field(..., title="Status")
    item: ItemOut | None = None
    problem: ProblemOut | None = None


class ComputedStatOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    stat_definition_id: UUID = Field(..., title="Stat Definition Id")
    formula: (
        LinearFormulaBodyOutput
        | ComparisonFormulaBodyOutput
        | SumFormulaBodyOutput
        | ContentsFormulaBody
    ) = Field(..., discriminator="kind", title="Formula")
    updated_at: AwareDatetime = Field(..., title="Updated At")


class ComputedStatPreviewIn(BaseModel):
    formula: (
        LinearFormulaBodyInput
        | ComparisonFormulaBodyInput
        | SumFormulaBodyInput
        | ContentsFormulaBody
        | None
    ) = Field(None, title="Formula")


class ControlledItemInstanceOut(BaseModel):
    entity_id: UUID = Field(..., title="Entity Id")
    title: str = Field(..., title="Title")
    weight: int | float | None = Field(..., title="Weight")
    height: int | float | None = Field(..., title="Height")
    price: int | float | None = Field(..., title="Price")
    rarity: int | float | None = Field(..., title="Rarity")
    hp: int | float | None = Field(..., title="Hp")
    armor: int | float | None = Field(..., title="Armor")
    container_entity_id: UUID | None = Field(..., title="Container Entity Id")
    quantity: int | None = Field(..., title="Quantity")
    prototype_ids: list[UUID] = Field(..., title="Prototype Ids")
    is_container: bool | None = Field(..., title="Is Container")
    descriptions: list[DescriptionOut] = Field(..., title="Descriptions")
    pictures: list[PictureRefOut] = Field(..., title="Pictures")
    physical_stats: list[StatValueOut] = Field(..., title="Physical Stats")
    economic_stats: list[StatValueOut] = Field(..., title="Economic Stats")
    destroyable_stats: list[StatValueOut] = Field(..., title="Destroyable Stats")
    damaging_stats: list[StatValueOut] = Field(..., title="Damaging Stats")
    tags: list[TagValueOut] = Field(..., title="Tags")
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    owner_entity_id: UUID | None = Field(..., title="Owner Entity Id")
    slug: str | None = Field(..., title="Slug")
    bound: bool = Field(..., title="Bound")
    visible_to_characters: bool = Field(..., title="Visible To Characters")


class CopyOut(BaseModel):
    steps: list[CopyStepOut] = Field(..., title="Steps")
    dry_run: bool = Field(..., title="Dry Run")
    previous: PreviousCopyOut | None


class CopyPlanOut(BaseModel):
    steps: list[CopyStepOut] = Field(..., title="Steps")
    collisions: list[CollisionOut] = Field(..., title="Collisions")


class EntityDetailOut(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    slug: str | None = Field(..., title="Slug")
    created_at: AwareDatetime = Field(..., title="Created At")
    updated_at: AwareDatetime = Field(..., title="Updated At")
    stats: list[EntityStatValueOut] = Field(..., title="Stats")
    stat_groups: list[EntitySummary] = Field(..., title="Stat Groups")
    information: list[InformationOut] = Field(..., title="Information")
    prototypes: list[EntitySummary] = Field(..., title="Prototypes")
    instances: list[EntitySummary] = Field(..., title="Instances")
    parent: EntitySummary | None
    quantity: int | None = Field(..., title="Quantity")
    children: list[EntitySummary] = Field(..., title="Children")


class HeldGroupOut(BaseModel):
    container: EntitySummary
    container_kind: ContainerKind = Field(..., title="Container Kind")
    path: list[EntitySummary] = Field(..., title="Path")
    carried: bool = Field(..., title="Carried")
    item_instances: list[ItemInstanceOut] = Field(..., title="Item Instances")


class ManagedScopeOut(BaseModel):
    tenants: list[ManagedTenantOut] = Field(..., title="Tenants")


class OwnedByResponse(BaseModel):
    groups: list[OwnedGroupOut] = Field(..., title="Groups")


class PackGivenOut(BaseModel):
    pack_id: UUID = Field(..., title="Pack Id")
    owner_entity_id: UUID = Field(..., title="Owner Entity Id")
    dry_run: bool = Field(..., title="Dry Run")
    created: list[PackItemOut] = Field(..., title="Created")


class PageReleaseAuthoredOut(BaseModel):
    items: list[ReleaseAuthoredOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PageStatDefinitionOut(BaseModel):
    items: list[StatDefinitionOut] = Field(..., title="Items")
    total: conint(ge=0) = Field(..., title="Total")
    page: conint(ge=1) = Field(..., title="Page")
    size: conint(ge=1) = Field(..., title="Size")
    pages: conint(ge=0) = Field(..., title="Pages")


class PublishedOut(BaseModel):
    id: UUID = Field(..., title="Id")
    slug: str = Field(..., title="Slug")
    name: str = Field(..., title="Name")
    description: str = Field(..., title="Description")
    kind: TenantKind
    published_at: AwareDatetime | None = Field(..., title="Published At")
    npcs_shared_with_gms: bool = Field(
        ...,
        description="Whether every GM of the library reads the GM-only text of the entries no campaign owns: the beings that are in no campaign, and what a copy of a repository brought, such as its catalog items. On (the default), every GM reads them; off, only the GMs who wrote an entry, or who share a campaign with whoever did, read it. An entry a campaign owns, because one of its characters holds it or stands in it, is read only by that campaign's GMs either way. Owners and Organizers read everything.",
        title="Npcs Shared With Gms",
    )
    created_by: UUID | None = Field(..., title="Created By")
    updated_by: UUID | None = Field(..., title="Updated By")
    release: ReleaseAuthoredOut


class UpdatesOut(BaseModel):
    repository_id: UUID = Field(..., title="Repository Id")
    changed: list[RowChangeOut] = Field(..., title="Changed")
    removed: list[RowRefOut] = Field(..., title="Removed")
    deleted_locally: list[RowRefOut] = Field(..., title="Deleted Locally")
    added: list[AddedOut] = Field(..., title="Added")
    attachments_added: list[AttachmentAddedOut] = Field(..., title="Attachments Added")
    attachments_removed: list[AttachmentChangeOut] = Field(..., title="Attachments Removed")
    attachments_deleted_locally: list[AttachmentChangeOut] = Field(
        ..., title="Attachments Deleted Locally"
    )
    names: dict[str, str] = Field(..., title="Names")
    release: ReleaseOut | None


class ControlledColumnOut(BaseModel):
    kind: Kind6 = Field(..., title="Kind")
    container: EntitySummary | None
    container_kind: ContainerKind | None = Field(..., title="Container Kind")
    path: list[EntitySummary] = Field(..., title="Path")
    carried: bool = Field(..., title="Carried")
    carried_by: EntitySummary | None
    contents_hidden: bool = Field(..., title="Contents Hidden")
    item_instances: list[ControlledItemInstanceOut] = Field(..., title="Item Instances")


class HeldByResponse(BaseModel):
    groups: list[HeldGroupOut] = Field(..., title="Groups")
    owners: list[EntitySummary] = Field(..., title="Owners")


class ControlledByResponse(BaseModel):
    columns: list[ControlledColumnOut] = Field(..., title="Columns")
    owners: list[EntitySummary] = Field(..., title="Owners")


PackItemOut.model_rebuild()
