import createClient, { type Middleware } from 'openapi-fetch';
import { z } from 'zod';
import { getAccessToken } from './auth';
import { API_BASE_URL } from './config';
import type { paths } from './lorenzo-schema';
import type { Page } from './types';

export type { components, paths } from './lorenzo-schema';

export class ApiError extends Error {
  readonly status: number;
  readonly problemType: string | undefined;

  constructor(message: string, status: number, problemType?: string) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.problemType = problemType;
  }
}

// RFC 9457 "Problem Details" - every apps/api error response is shaped this
// way (errors.py/exceptions.py, ADR 0020). Deliberately permissive (every
// field optional) since we don't control this shape - a slightly-
// different-than-expected problem body should still produce a readable
// error, not a second failure. Same treatment apps/loot-bot's own
// lorenzo-client.ts already gives it.
const problemSchema = z.object({
  type: z.string().optional(),
  title: z.string().optional(),
  detail: z.string().optional(),
});

function toApiError(error: unknown, status: number): ApiError {
  const parsed = problemSchema.safeParse(error);
  const problem = parsed.success ? parsed.data : undefined;
  return new ApiError(
    problem?.detail ?? problem?.title ?? `Request failed (${status}).`,
    status,
    problem?.type,
  );
}

// Attaches the bearer token to every request rather than each lib/*.ts
// call site doing it - throwing ApiError(401) up front (before a request
// the API would reject anyway goes out) reproduces the old apiFetch's own
// "not logged in" short-circuit.
const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const accessToken = await getAccessToken();
    if (!accessToken) {
      throw new ApiError('Not logged in.', 401);
    }
    request.headers.set('Authorization', `Bearer ${accessToken}`);
    return request;
  },
};

// The generated, typed API client (openapi-fetch over lorenzo-schema.d.ts,
// generated by `pnpm run generate-client` from apps/api's own OpenAPI
// schema - see package.json) - mirrors apps/loot-bot's own
// lorenzo-client.ts pattern. A path typo, or a response field a route no
// longer sends, is now a build-time type error here instead of a silent
// undefined at runtime the way the old hand-rolled apiFetch<T>(path) left it.
export const client = createClient<paths>({ baseUrl: API_BASE_URL });
client.use(authMiddleware);

// Unwraps an openapi-fetch result into its data, or throws a typed
// ApiError - every lib/*.ts function below calls this once around its own
// client.GET/POST/PUT/PATCH/DELETE, rather than repeating the
// `if (error !== undefined) throw ...` check at every call site the way
// apps/loot-bot's own client does (each of its many methods, one per bot
// command, inlines its own copy) - this app's client only ever has this
// one module as a caller, so centralizing it here has no equivalent
// downside.
export async function unwrap<T>(result: {
  data?: T;
  error?: unknown;
  response: Response;
}): Promise<T> {
  if (result.error !== undefined) {
    throw toApiError(result.error, result.response.status);
  }
  return result.data as T;
}

// Every list endpoint in this API is paginated (fastapi-pagination's own
// default Params: size defaults to 50, capped at 100 - ADR 0020) - a single
// GET silently truncates to whichever page came back, with nothing past it
// ever fetched. Fetches page 1, then every remaining page in parallel (the
// page count is known from the first response's own `pages`), and flattens
// the result - for a caller that wants "every item," not one page of them.
// getPage is the typed client call for one page, so this stays agnostic of
// which endpoint it's paging.
export async function fetchAllPages<T>(getPage: (page: number) => Promise<Page<T>>): Promise<T[]> {
  const first = await getPage(1);
  if (first.pages <= 1) return first.items;
  const rest = await Promise.all(Array.from({ length: first.pages - 1 }, (_, i) => getPage(i + 2)));
  return [first.items, ...rest.map((page) => page.items)].flat();
}

// The largest page size the API allows (ADR 0020) - fewest round trips.
export const MAX_PAGE_SIZE = 100;
